### ISSUE TITLE
WPF generates Assembly Version Info twice

### ISSUE THREAD

**Issue by virzak** [dotnet/Nerdbank.GitVersioning#1009]
Targets with `DependsOnTargets="GetBuildVersion" BeforeTargets="GenerateAssemblyVersionInfo"` as mentioned in https://github.com/dotnet/Nerdbank.GitVersioning/issues/409#issuecomment-823362561 run twice in WPF. It this a WPF issue or can something be done about it in a user project?

Steps to reproduce:

```pwsh
dotnet new sln -o NbgvTestWpf
cd NbgvTestWpf
dotnet new wpf -o NbgvTestWpf
dotnet sln add NbgvTestWpf
dotnet new gitignore
dotnet new buildprops --use-artifacts
git init
nbgv install
git add .
git commit -am "Initial commit"
```

Add to NbgvTestWpf.csproj:
```xml
<Target Name="SetBuildBranch" DependsOnTargets="GetBuildVersion" BeforeTargets="GenerateAssemblyNBGVVersionInfo">
  <Message Text="Should fire once" Importance="High" />
</Target>
```

The output is:
```
🚀  dotnet build -bl
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Should fire once
  Should fire once
  NbgvTestWpf -> Q:\Code\Sandbox\NbgvTestWpf\artifacts\bin\NbgvTestWpf\debug\NbgvTestWpf.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.96
```

<img width="346" alt="image" src="https://github.com/dotnet/Nerdbank.GitVersioning/assets/6209775/d1e1c427-c28c-4280-b107-9592faabce55">

**Comment by AArnott** [comment]
MSBuild itself guarantees a target only executes once, but WPF turns one project into two by executing a variant of itself, and many of its targets run in both places. This then isn't a NB.GV-specific issue, and in fact versioning information is typically important to both the 'inner' build and the 'outer' build, so NB.GV itself running twice is probably a good thing.

If you don't want your particular target to run twice, you'll have to detect which of the two builds your target might run in and skip the target, probably by a Condition on your Target.

**Comment by virzak** [comment]
Closing

**Comment by virzak** [comment]
Also, I noticed that the `RootNamespace` is generated from the 'inner build' and I get: 

```cs
internal const string RootNamespace = "NbgvTestWpf_hndhyswj_wpftmp";
```

which can't be used. Is that a bug?
