### ISSUE TITLE
Warning about PrivateP2PCaching.proj

### ISSUE THREAD

**Issue by thomas-ravkilde** [dotnet/Nerdbank.GitVersioning#1040]
I have the same issue as #787. If I understand correctly, this issue should have been circumvented for v3.6 by #847. However, I still get the issue with v3.6.133. I'm not using a graph build, AFAIK:

`Directory.Build.props`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Condition="!Exists('packages.config')">
      <PrivateAssets>all</PrivateAssets>
      <Version>3.6.133</Version>
    </PackageReference>
  </ItemGroup>
</Project>
```

**Comment by AArnott** [comment]
Code inspection suggests that the fix is in fact present in 3.6.133. I'm going to need more information for this to be actionable. 
Where are you seeing the warning? What version of the software are you on? Can you share a minimal repro?

**Comment by thomas-ravkilde** [comment]
Note that the warnings show up for .NET Framework 4.8 projects but not .NET 8.0 projects. I think, I forgot to mention that.

**Comment by thomas-ravkilde** [comment]
Sound great. Let me know if you need me to test anything.
