### ISSUE TITLE
override NGBV produced version

### ISSUE THREAD

**Issue by KunalSaini** [dotnet/Nerdbank.GitVersioning#1053]
Hi,
I am trying to set NuGet package version of in a csproj file like below.
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>2.2.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.6.133" PrivateAssets="all" />
  </ItemGroup>
</Project>
```
This project is not in a git repository.
The project does not have a `version.json` file.
I would have expected it to produce `v2.2.2` of NuGet package on `dotnet build` , however it produces `v0.0.0-g`

I tried passing in version explicitly 
`dotnet build /p:Version=2.2.2` , still it produces the `v0.0.0-g` package version.

I am using dotnet sdk 8.0.102 for build, if that matters.

Question: how do i override this NBGV behavior.

**Comment by AArnott** [comment]
Question: Why are you installing the Nerdbank.GitVersioning package if you're not in a git repo and don't want it to set the version?

**Comment by KunalSaini** [comment]
This is just an example I put together to understand the versioning override mechanism, in reality, we have a lot of separate .net repositories in git and we maintain a custom sdk that brings/enforces common packages/functionality to all repositories/solutions. We are considering putting NBGV in our custom sdk so thats its available to all repositories. And each repository owner can switch to NBGV on their own pace (by introducing proper `version.json` that makes sense for their repository)
My initial understanding was that if `version.json` is absent in a repository , the old/existing versioning mechanism will continue to work, for example lot of repositories use msbuild switch to specify version in our CI/CD environment.
However, when i tries that, it failed to set the version number if the repo is using NBGV.

**Comment by AArnott** [comment]
I see. No, the behavior you're seeing is the intended behavior. That is, elements of it activate even without git and without a version.json file.
You can check out our [msbuild docs](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/msbuild.md) for how to customize the output, but having the package installed without an intention to use it hasn't been a scenario so far.

**Comment by cabillin** [comment]
@AArnott, I guess I'm reporting the 1st use case where the package installed without an intention to use it. Specifically, the package is installed by one of our dependencies (NGBV is a transitive dependency). I need my NuGet package's version to come from the csproj VersionPrefix & VersionSuffix.

Our repo contains several C# projects. I've confirm the dotnet/msbuild command works correctly in the projects that do not have NGBV as a transitive dependency.

**Comment by AArnott** [comment]
> the package is installed by one of our dependencies (NGBV is a transitive dependency)

That sounds like the issue to solve. NB.GV should only ever be used with `PrivateAssets="all"` on the `PackageReference` because it is a development dependency. That will prevent it from ever showing up as a transitive dependency.

**Comment by vanwx** [comment]
I have a specific packaging requirement and I'm hoping you can assist me.

I'm using the dotnet pack command within the **DotNetCoreCLI** task, and it correctly generates packages with the `BuildNumber` generated by NerdBank.GitVersioning.

My goal is to append a `-prerelease` suffix to the nuget package version specifically when the build is triggered by a Pull Request. I've attempted to use environment variables in conjunction with the `versioningScheme` option, but it appears the package generation process (GetBuildVersionCore) resets or overrides this variable.

```yaml
- task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: 'src/**/*.csproj'
      packDirectory: $(Build.ArtifactStagingDirectory)/packages
      nobuild: true
      versioningScheme: byEnvVar
      versionEnvVar: PackageVersion
      verbosityPack: Normal
      buildProperties: 'Version=$(PackageVersion)'

```


```
Starting: Pack
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.256.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
/opt/hostedtoolcache/dotnet/dotnet pack /agent/_work/4/s/src/MyProject/MyProject.csproj --output /agent/_work/4/a/packages --no-build /p:Configuration=Release /p:Version=2.0.93-prerelease /p:PackageVersion=2.0.93-prerelease --verbosity Normal
Build started 05/23/2025 04:44:40.
     1>Project "/agent/_work/4/s/src/MyProject/MyProject.csproj" on node 1 (pack target(s)).
     1>Project "/agent/_work/4/s/src/MyProject/MyProject.csproj" (1) is building "/home/AzDevOps/.nuget/packages/nerdbank.gitversioning/3.7.115/build/PrivateP2PCaching.proj" (2) on node 1 (GetBuildVersion_Properties target(s)).
     2>GetBuildVersionCore:
         Building version 2.0.93.28716 from commit 702c45aaf85debfb9be02218db9a98fzzz779ba2
     2>Done Building Project "/home/AzDevOps/.nuget/packages/nerdbank.gitversioning/3.7.115/build/PrivateP2PCaching.proj" (GetBuildVersion_Properties target(s)).
     1>GenerateNuspec:
         The package MyProject.2.0.93-g702c45aaf8 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
         Successfully created package '/agent/_work/4/a/packages/MyProject.2.0.93-g702c45aaf8.nupkg'.
     1>Done Building Project "/agent/_work/4/s/src/MyProject/MyProject.csproj" (pack target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.02

```


Do you have a recommended workaround to dynamically add this `-prerelease` suffix to the package version during Pull Request builds while still utilizing the BuildVersion from NB.GV?

**Comment by AArnott** [comment]
@vanwx Please open a new issue or (even better) use the Discussions tab for your question rather than commenting on a long-closed issue.

tip: You mentioned a `versioningScheme` option -- There is no such option by that name in this tool.
