### ISSUE TITLE
Build error on Linux when building esproj

### ISSUE THREAD

**Issue by scannon5** [dotnet/Nerdbank.GitVersioning#1092]
After adding nbgv to a solution we get an error when compiling on Linux if the csproj references an esproj project.

To reproduce:

1. In Visual Studio create a new "Angular and ASP.NET Core" project targetting .NET 8.
2. Initialize git repo
3. On Linux: `dotnet build` - works ok
4. Install nbgv
5. On Linux: `dotnet build` - build fails with:

`/usr/lib/dotnet/sdk/8.0.108/NuGet.targets(156,5): error : Invalid restore input. Invalid target framework 'unsupported'. Input files: /home/fred/AngularApp/angularapp.client/angularapp.client.esproj. [/home/fred/AngularApp/AngularApp.Server/AngularApp.Server.csproj]`

If you remove the reference to the esproj from the server .csproj file the build works. Also works ok building on Windows. It's the combination of nbgv, Linux and referencing that esproj that breaks it.

Apologies if this is not an nbgv issue, or I'm doing something wrong. Searching brings back nothing similar.

**Comment by AArnott** [comment]
Can you share the binlog of your attempt? 
How are you installing NB.GV? 

I'm not familiar with esproj. My guess is that your method of installation impacts the esproj itself, and that it would fail the build if built directly, regardless of the project reference from the csproj.

**Comment by AArnott** [comment]
It looks like esproj doesn't support nuget package references. I suggest then that you modify your Directory.Build.props file to use a condition to exclude NB.GV for it.

Something like this:

```xml
<PackageReference Include="Nerdbank.GitVersioning" Condition="'$(MSBuildProjectExtension)'!='.esproj'" />
```

**Comment by AArnott** [comment]
I suggest you also file a bug against esproj, so they can investigate why they lack targetframework/nuget support only on linux.

**Comment by scannon5** [comment]
Many thanks for your time on this, appreciate it. The workaround works.

I'll file a bug as suggested. Would that be in the aspnetcore repo? I'm guessing that's where the problem is.

**Comment by AArnott** [comment]
> Would that be in the aspnetcore repo? I'm guessing that's where the problem is.

Your guess will be better than mine. I've never even created an esproj before.
