### ISSUE TITLE
AssemblyVersion misreported as 0.0.0.0

### ISSUE THREAD

**Issue by stuarthallows** [dotnet/Nerdbank.GitVersioning#1094]
In a .NET core console app I have the assembly version set as 2.2.2 in the .csproj.

```xml
  <PropertyGroup>
    <AssemblyVersion>2.2.2</AssemblyVersion>
    <Version>1.1.1</Version>
    <FileVersion>3.3.3</FileVersion>
  </PropertyGroup>
```
When I build the project the generated `ThisAssembly` gives the assembly version as 0.0.0.0. I wonder what I'm missing?

```csharp
[assembly: System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
internal static partial class ThisAssembly {
    internal const string AssemblyConfiguration = "Debug";
    internal const string AssemblyVersion = "0.0.0.0";
    internal const bool IsPrerelease = false;
    internal const bool IsPublicRelease = false;
}
```

Nerdbank.GitVersioning: 3.6.143

**Comment by AArnott** [comment]
If you're using NB.GV, you shouldn't be setting the version in your project file anymore. You should be using version.json. Check out our readme file for more info.
