### ISSUE TITLE
How to remove the Git ID information from the product version in WPF?

### ISSUE THREAD

**Issue by shushu789** [dotnet/Nerdbank.GitVersioning#1099]
In my WPF project, I referenced "Nerdbank.GitVersioning" as a NuGet package and used the following basic JSON configuration:

`{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.2-dev",
  "assemblyVersion": {
    "precision": "build"
  },
  "publicReleaseRefSpec": [
    "^refs/heads/master$"
  ]
}`

When I build or publish, the product version in the properties of the exe or dll contains part of the Git ID, like "1.2.5-dev+b962fb6c52". Sorry, I'm a beginner, but I want to exclude the Git ID part (“+b962fb6c52”). I believe that after the release, the end users typically don’t need this information. I saw in the documentation that it would be automatically removed, but I found that it only happens when publishing a NuGet package. For WPF or other applications, is it possible to remove it? If I've missed some relevant instructions, please forgive me.

![image](https://github.com/user-attachments/assets/ceaa7a4b-4bee-4a55-bac4-75f4d1001530)

![image](https://github.com/user-attachments/assets/50db88f3-6155-4b69-992c-d7907d72b832)

Environment:
Visual Studio 2022  
Windows 10  
Nerdbank.GitVersioning 3.6.143

**Comment by AArnott** [comment]
There isn't a built-in way to do this. You can rewrite an msbuild property (see our md file under the `doc/` folder) to customize it if you wish.

IMO though, ordinary users won't venture here unless customer support tells them to, in which case the git commit may be very useful.
