### ISSUE TITLE
PublicRelease not getting correctly detected?

### ISSUE THREAD

**Issue by hayer** [dotnet/Nerdbank.GitVersioning#1118]
I have a repo that looks something like this
```
README.md
docs/
src/
    version.json   (1)
    projcet1/
        Project1.csproj
        version.json   (2)
```

The "outer" `version.json` (1)  looks like this

```
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/main/src/NerdBank.GitVersioning/version.schema.json",
  "publicReleaseRefSpec": [
    "^refs/heads/master$",
	  "^refs/heads/main$"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  }
}
```

The "inner" `version.json` (2) looks like this
```
{
	"$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/main/src/NerdBank.GitVersioning/version.schema.json",
	"version": "3.2",
	"inherit": true,
	"pathFilters": ["."]
}
```

When running `dotnet build .` inside `src/project1` in the `master` branch I expect `PublicRelease` to be `true`. Instead it is _always_ false..

I was expecting the version number to be `"NuGetPackageVersion": "3.2.0"` instead I am getting `"NuGetPackageVersion": "3.2.0-g5abbf19912"`.
Probably something I've missed?

Edit:
Reasoning for doing this is I have several projects inside "src", each with its own separate `version.json` file since I want to only increase the version of the NuGet packages when there are commits affecting that specific sub folder.

Edit edit:
If I set `version` in `version.json` (1) and runs `nbgv get-version` in `src` it _correctly_ detects it.

**Comment by AArnott** [comment]
> If I set version in version.json (1) and runs nbgv get-version in src it correctly detects it.

A version.json file must either inherit or define a version. This is described in the schema for the file.

https://github.com/dotnet/Nerdbank.GitVersioning/blob/2009e91eb7d5c0a530db528d702b780d2613b080/src/NerdBank.GitVersioning/version.schema.json#L5-L28

If you're editing your version.json inside a JSON editor that supports schemas, a problem should report this. When I put your file into VS Code for example, this is what I see:

![Image](https://github.com/user-attachments/assets/7c5a3dab-f60f-46fb-b75a-f825b9dd1d83)

**Comment by hayer** [comment]
@AArnott did not make any difference.
Added `"version": "99.99"` to the `version.json` (1) and `nbgv get-version -f json` inside `project1` still shows `"PublicRelease": false`.

**Comment by AArnott** [comment]
I'm confused. First you said:

> If I set version in version.json (1) and runs nbgv get-version in src it correctly detects it.

Then you said:

> Thou that did not make any difference 😟
Added "version": "99.99" to the version.json (1) and nbgv get-version -f json inside project1 still shows "PublicRelease": false.

It sounds like you're contradicting yourself.

> seems like GitLab is making a mess out of this

That could be. Some cloud build systems don't actually check out the branch, but rather check out a specific commit with a detached HEAD. That will throw NB.GV's detection of public release branches off. That said, we have special support to work anyway with some of these, [including GitLab](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/src/NerdBank.GitVersioning/CloudBuildServices/GitLab.cs). But maybe GitLab changed in a way that broke our special checks?

**Comment by hayer** [comment]
What I meant was that it used the version defined in `version.json` (1), not the version set in `version.json` (2). Sorry for the confusion.

The pipeline itself added a commit in specific scenarios, which caused my confusion. Sorry for taking up your time.
