### ISSUE TITLE
`vcxproj` generates a different `ProductVersionRaw` compared to `csproj`

### ISSUE THREAD

**Issue by vitezslav-popovsky-solarwinds** [dotnet/Nerdbank.GitVersioning#1124]
We use NBGV in our pipeline for .NET and native Windows binaries with the same setting (`version.json`). However, NBGV produces different `ProductVersionRaw` for .NET and native Windows binaries:

```powershell
PS D:\> (Get-Item CppNative.exe).VersionInfo.ProductVersionRaw

Major  Minor  Build  Revision
-----  -----  -----  --------
2024   4      0      0
```

```powershell
PS D:\> (Get-Item DotNet48.exe).VersionInfo.ProductVersionRaw

Major  Minor  Build  Revision
-----  -----  -----  --------
2024   4      0      2620
```

this discrepancy is due to the fact, that `NativeVersionInfo` uses `AssemblyVersion`
https://github.com/dotnet/Nerdbank.GitVersioning/blob/88f4c2d70905ac5980759daed5392279d263b59a/src/Nerdbank.GitVersioning.Tasks/NativeVersionInfo.cs#L169-L172

as a source for `PRODUCTVERSION`

https://github.com/dotnet/Nerdbank.GitVersioning/blob/88f4c2d70905ac5980759daed5392279d263b59a/src/Nerdbank.GitVersioning.Tasks/NativeVersionInfo.cs#L42-L45

Based on the `NativeVersionInfo` code mentioned above, it appears that this behavior is intentional. Could we at least add a setting or switch that allows users to ensure the `ProductVersionRaw` for `vcxproj` matches that of `csproj`?

**Comment by vitezslav-popovsky-solarwinds** [comment]
@AArnott I've just opened #1125. 
For our needs, removing `AssemblyVersion` from `NativeVersionInfo` entirely would be acceptable, but it could be a "breaking change" for others. Thus, I added a new switch that defaults to the current behavior.

**Comment by AArnott** [comment]
>  it could be a "breaking change" for others

I'm much less experienced with native binary versioning. How could making the version of a native binary more precise be a breaking change for them?

**Comment by vitezslav-popovsky-solarwinds** [comment]
> How could making the version of a native binary more precise be a breaking change for them?

Perhaps someone prefers having `FileVersionRaw` and `ProductVersionRaw` be different and is satisfied with the current solution that has been in place since 2017. Hard-coding the change would disappoint these users in the next `Nerdbank.GitVersioning` release.
