### ISSUE TITLE
Documentation Unclear - Examples needed

### ISSUE THREAD

**Issue by sebastiano-pera-netventure** [dotnet/Nerdbank.GitVersioning#1137]
Hi, I'm a 37 yo Full Stack developer, I've got 6+ years in .NET programming and 5+ years into WebUi programming (vanilla, angular, vue). 
I'm working on a project in a MonoRepo with a C# backend and a Vue3 WebApp and I would like those projects to have a matching self-mantained versioning through git tags. 
BTW the project is built via a GitLab pipeline.
I've stumble upon the project which seems very complete and should solve perfectly my task, but I'm struggling so hard to find even basic examples on how to use is and what result should I expect/where to look for it. 
Even after some googling I can't get simple examples to start from. How do you guys made use of it?

I've followed the instructions for the [.NET nuget](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/nuget-acquisition.md) and after the build, ~~my assembly or exe file version(those you find with right click) didn't change at all.~~
I've checked the bin folder and I've seen that the version was set as specified by the version.json file, even thought the whole thing was a bit obscure.

I've also installed the [NPM version](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/npm-acquisition.md), and then? I've already got the default version.json, where am I supposed to see the result? Should I expect to see any result at all? How do I test it? 

There should be a minimalistic step by step guide that beginners can follow to get a reproducible behaviour, which is an essential entry point to start with and grow experimenting.

Thanks

**Comment by AArnott** [comment]
> I would like those projects to have a matching self-mantained versioning through git tags.

If that's really what you want, this isn't the tool for you. NB.GV computes versions based on a `version.json` file and git history. It doesn't base it on anything mutable like tags or branches. Other git versioning projects can help you if you want a tag to change the computed version.

> Why isn't there a minimalistic default output to give the user a feeling they're on the right path.

NB.GV doesn't add versions or any other output. It only controls versions where versions already appeared. If you want to see the effect of NB.GV you should look at one of the versions in your build artifacts.

**Comment by AArnott** [comment]
> this wasn't clear to me until I've spent hours trying.

I'm not sure how I can be more clear on that point. It's front and center of the README:

![Image](https://github.com/user-attachments/assets/a9a89adb-1283-4f6b-ade7-40ad70ac7b7c)

>> If you want to see the effect of NB.GV you should look at one of the versions in your build artifacts.

> but anyway I think it may be clearer in the docs. Again, a small guide could help people try out this valuable project 

That's a reasonable suggestion. I may take what @KalleOlaviNiemitalo wrote up and stick it somewhere prominent.
