### ISSUE TITLE
Docs should include `assemblyVersion` JSON object option, and note to commit file

### ISSUE THREAD

**Issue by Tadimsky** [dotnet/Nerdbank.GitVersioning#170]
Hey,
I ran into an issue where the `AssemblyVersion` was not being set for my DLLs. I then saw that it needs to be specified in the `version.json` file.
(By the way the [docs](https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/versionJson.md#file-format) do not contain info for the full options for `assemblyVersion`).

I then updated my `version.json` file to this:
```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "inherit": true,
  "version": "1.0",
  "assemblyVersion": {
    "precision": "revision"
  }
}
```

However, when I build I still have no AssemblyVersion set (it is always 1.0.0.0):
```cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.262.48688")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.262+g30beddd2a1")]
internal static partial class ThisAssembly {
    internal const string AssemblyVersion = "1.0.0.0";
    internal const string AssemblyFileVersion = "1.0.262.48688";
    internal const string AssemblyInformationalVersion = "1.0.262+g30beddd2a1";
    internal const string AssemblyName = "ContentServiceFrontend";
    internal const string AssemblyTitle = "ContentServiceFrontend";
    internal const string AssemblyConfiguration = "Debug";
    internal const string RootNamespace = "Microsoft.Intentional.ContentService.Frontend";
}
```

Am I missing something?

**Comment by Tadimsky** [comment]
Aha - it looks like it's not enough to just save the `version.json` file. I had to commit the change for this to work.
I didn't want to commit it until I knew it worked :)

**Comment by AArnott** [comment]
IIRC you don't have to commit for it to work, but you do have to commit to get a non-zero git height. So if you set the version to 2.0, you'd see the difference. 
Thanks for the tip on the docs. I'll keep the issue open to track that.

**Comment by Tadimsky** [comment]
Oh, is the versioning for `AssemblyVersion` separate then from the other versioning? When I committed and built again it set the `AssemblyVersion` to the same version as the `AssemblyFileVersion`.

**Comment by AArnott** [comment]
The assembly version defaults to just the major.minor of the assembly file version. But your version.json file overrode that.

**Comment by Tadimsky** [comment]
Ok, so that's why it was `1.0.0.0` before? Since that was from the `1.0` part of AssemblyFileVersion.
So the fact that I had to commit the change in order to make `AssemblyVersion` use the new changes in `version.json` is expected.
