### ISSUE TITLE
Support height in fourth version part for NuGet

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/Nerdbank.GitVersioning#401]
While the majority of uses can be done with with a major.minor version and the third/patch as the auto increment, there is sometimes a need for a four part version.

If I use 1.2.3 as the version, the version shows as 1.2.3.1, but the NuGetPackageVersion shows as 1.2.3.

I believe this should be supported. I'd want 1.2.3.1 as the package version.

**Comment by onovotny** [comment]
already works.

**Comment by AArnott** [comment]
@bradwilson also wanted something similar: height in the 4th part of *file* version, but no 4th part in the nuget version.

**Comment by bradwilson** [comment]
My usage is slightly different (I want height as part of the prerelease information for the NuGet package, so 1.2.3-pre.1+hash)

**Comment by azeno** [comment]
@bradwilson I believe this was possible in version 2, see #477

**Comment by ap0llo** [comment]
I have a use-case for this (the first 3 parts of the package version should be constant and I would just like to automatically increment the 4th part).

Would you accept a PR adding this?

I'd suggest to add a `precision` property to `nugetPackageVersion` in version.json (analogous to the `assemblyVersion` settings)

**Comment by AArnott** [comment]
Sure. That seems like a reasonable design. Thanks for offering the PR.

**Comment by ap0llo** [comment]
I implemented support for this in #719.

Thinking about it, would it also make sense to have something similar for the cloud build number so the build number could be configured to match the NuGet package version in the case a 4th version field is used?

**Comment by AArnott** [comment]
Yes, we want cloud build numbers to be mostly unique as well, so if height has been moved to the 4th integer, the cloud build number should include that as well.

**Comment by ap0llo** [comment]
I had an idea for an alternative way to solve this.

Instead of adding a `precision` setting, what do you think about automatically including the 4th version field in the NuGet package version if 3 fields are configured in `version.json`.
The same behavior could then be applies to the cloud build number.

**Comment by ap0llo** [comment]
I experimented with the idea of always emitting a 4-part NuGet package version if there are 3 parts configured in `version.json` but I think that would be a breaking change (at least it breaks a lot of tests) so it would probably be best to go with the `precision` setting anyways.

Would that also be your preferred solution for the cloud build number?
I'd be happy to add that as well

**Comment by AArnott** [comment]
I think cloud build number could go the way you suggest of automatically including the 4th integer if 3 are specified in version.json.
For nuget package versions we should _not_ go that way, because a lot of folks specify 3 versions to control their nuget versions completely, as they consider their versions to be part of their brand.

**Comment by ap0llo** [comment]
> I think cloud build number could go the way you suggest of automatically including the 4th integer if 3 are specified in version.json. 
> For nuget package versions we should _not_ go that way, because a lot of folks specify 3 versions to control their nuget versions completely, as they consider their versions to be part of their brand.

Okay, in that case, #719 is the right implementation for the NuGet package version.

I'll prepare another PR for the cloud build number change.
