### ISSUE TITLE
New CodeAnalysis attribute breaking nanoFramework builds

### ISSUE THREAD

**Issue by josesimoes** [dotnet/Nerdbank.GitVersioning#441]
Hi,

Recently this line was added:
https://github.com/AArnott/Nerdbank.GitVersioning/blob/35b087bc50864c8da8b9abfd2124f59ee31a74dd/src/Nerdbank.GitVersioning.Tasks/AssemblyVersionInfo.cs#L545

Bring the `System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage` attribute.
Because we don't have that attribute in nanoFramework this is breaking our builds.

If you recall we had a previous contact in #346 because of a similar problem.

Any chance that can be wrapped with compiler defs?

**Comment by AArnott** [comment]
Sure. I'm working on a fix for you. 

To help keep this in a working state for nanoFramework, I'm interested in a PR that adds a test to this repo that would fail when the generated code can't compile on nanoFramework. But I'd like to first understand what that PR would bring in. Would it add prereqs to develop in this repo or can it all come from nuget?

**Comment by josesimoes** [comment]
Thank you very much for the prompt fix!

To add a test for a nF build it would require a partial install of our VS extension.
Then a simple project can be build to test this.

We have an Azure Pipelines task that does exactly that.
(that's a private task, I'll send you an invite)

The usage would be something like this:
https://github.com/nanoframework/nf-tools/blob/d44a97afcbde6184079dbce5be10c940be01a7af/azure-pipelines-templates/class-lib-build.yml#L155

**Comment by AArnott** [comment]
Hmmm.... What does installation look like on a dev box? Any odd prereq will deter folks from contributing to NB.GV, and we have several that periodically contribute.

**Comment by josesimoes** [comment]
That would be a simple VS extension. There are versions for VS2017 and VS 2019:
https://github.com/nanoframework/nf-Visual-Studio-extension#build-status

**Comment by AArnott** [comment]
Well we rarely change this area, so I guess we can see how far we get without in-repo validation again.
Thanks for your flexibility.
