### ISSUE TITLE
trying to understand how this works

### ISSUE THREAD

**Issue by thomasd3** [dotnet/Nerdbank.GitVersioning#448]
how is the code invoked?
I have installed the tool and I am building docker-containers.

at which point does the version info get embedded in the assembly? is this added to the build pipeline?

**Comment by AArnott** [comment]
Did you read the README? It's all there (or linked from there).

Installing the tool alone doesn't do anything to your projects. To get version info added to your assembly you need to reference the `Nerdbank.GitVersioning` nuget package. The tool *can* do this for you, or you can just use the standard nuget commands you're already familiar with.
