### ISSUE TITLE
Add more information to ThisAssembly

### ISSUE THREAD

**Issue by mivor** [dotnet/Nerdbank.GitVersioning#455]
Hi,

I'm using GitVersioning for a desktop application and would like to display the app version.

For this it would be ideal to have a version available in ThisAssembly that is similar to the CloudVersion or NugetPackageVersion which have a different shape depending on publicRelease and preRelease.

For example:
Non-public release with preRelease: 0.2.23-beta+143f2c6f79
Public release with preRelease: 0.2.23-beta
Public release: 0.2.23

What do you think?

**Comment by AArnott** [comment]
Sure, that makes sense. It sounds equivalent to #409.
