### ISSUE TITLE
ExcludeFromCodeCoverage in generated code breaks net20 targets

### ISSUE THREAD

**Issue by AArnott** [dotnet/Nerdbank.GitVersioning#456]
As @amis92 identifies in https://github.com/AArnott/CodeGeneration.Roslyn/pull/198#issuecomment-604144539

**Comment by AArnott** [comment]
@amis92 Why is net20 an interesting target for your use case at this point?

**Comment by amis92** [comment]
TBH I have no idea whatsoever who can need that. It just always were one of the targets for the Attributes package. I might have gotten a question for net35 support at some point though. 🤷‍♂️

**Comment by AArnott** [comment]
Ok, well, since we support multiple languages (C#, F#, VB), changing the condition's isn't *particularly* as easy as it might sound. So I'd rather not go to the trouble if it isn't warranted. I suggest we cut net20 support from CG.R.

**Comment by lamronby** [comment]
For what it's worth, it's not just net20 targets - it's all .net versions prior to 4: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=netframework-4.5#moniker-applies-to

**Comment by rseanhall** [comment]
WiX v4 is using Nerdbank.GitVersioning. Thanks for this library.

There are two cases where we're still targeting `net20` - [DTF](https://github.com/wixtoolset/Dtf) and [Managed Bootstrapper Applications](https://github.com/wixtoolset/balutil). DTF is the managed wrapper around many Win32 API's around MSI's and is used extensively by custom actions. Managed BA's are the user's code in WiX's bootstrapper (Burn). In both cases, our users may still be targeting versions of Windows that does not have .NET 4.x (even though those versions of Windows are no longer supported by Microsoft). I might be able to help if you're still interested in supporting `net20`.

**Comment by AArnott** [comment]
Thanks for offering help, @rseanhall. What if you just set the property to disable `ThisAssembly` code generation for these net20 projects? Do you need it?

**Comment by rseanhall** [comment]
We're not using the `ThisAssembly` class, so if we can disable that code generation then that would work.

**Comment by AArnott** [comment]
@rseanhall #292 tracked making `ThisAssembly` a suppressible feature. If you wanted to contribute, I think I'd prefer 'fixing' that issue rather than this one, if it's all the same to you.
