### ISSUE TITLE
using height as patch

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/Nerdbank.GitVersioning#462]
I try to use GitVersioning with following `version.json`
```json
{
    "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
    "version": "0.1",
    "nugetPackageVersion": {
        "semVer": 2
    }
}
```

The schema allows a version of `0.1` and from its documentation I would assume that a version like `0.1.x` will be generated where `x` is the height.

However I get `System.FormatException: The value "0.1.{height}" is not a valid semantic version.` Which seems odd, since (if `{height}` is replace with a number) 0.1.2 is a valid version number.

**Comment by AArnott** [comment]
Your file above looks fine. Have you *committed* your version.json file? Do you perhaps have a prior commit of version.json in your git history that had `"0.1.{height}"` as your value for the `version` property? If so, you have to either rebase and remove all invalid version.json files from your git history, or you have to author a commit that *removes* `version.json` completely, and then a *new* commit (two commits total -- don't squash) that re-introduces the version.json file with valid content.

**Comment by LokiMidgard** [comment]
Thanks for the fast response.

I had a preior version of `version.json`. I removed it and added a new variant in a second commit. Maybe I have commited "somthing" wrong. It's now working with 3 commits 

1. remove 
2. something else
3. recreation of `version.json`

Now it works.

**Comment by AArnott** [comment]
I don't know why an intermediate commit between the removal and addition was required, but I'm glad you got it working.
