### ISSUE TITLE
Build in docker with Nerdbank.GitVersioning

### ISSUE THREAD

**Issue by vchirikov** [dotnet/Nerdbank.GitVersioning#467]
Hi @AArnott , I am using build in docker and I have some question about it.
As you may know this is a bad idea to copy `.git` folder to docker build context (because the folder can be large) So do you have any ideas how to use Nerdbank.GitVersioning without `.git`?
I think we can add some `Condition` to `GetBuildVersion` target and if it is set just read output parameters from props file / env variables.
Or maybe you already have some ideas about it?

**Comment by vchirikov** [comment]
Related https://github.com/dotnet/Nerdbank.GitVersioning/issues/416

**Comment by AArnott** [comment]
Yes, this is a duplicate of #416. I prescribe how to do it there. If you have further questions, let's address it on that issue.
