### ISSUE TITLE
Make output of "prepare-release" command machine-readable

### ISSUE THREAD

**Issue by ap0llo** [dotnet/Nerdbank.GitVersioning#481]
I'm running the `prepare-release` command as part of a script that performs other actions required for release.

The script needs the name of the branch that `prepare-release` created. 
Currently this means either 

 - parsing the log output or 
- duplicating the logic to determine the name of the branch from the settings in `version.json` in the script.

I this having an option to output the information in a machine-readable way would be preferable.

I propose to add a `--format` option to the `prepare-release` command that emits the relevant information as json (analogous to the `--format` option of  `get-version`).

Would you accept a PR adding this feature?

The output could look something like this (branching off `0.2` from `master`):

```json
{
    "releaseBranch" : {
        "name" : "release/v0.2",
        "version" : "0.2"
    },
    "devBranch" : {
       "name" : "master", 
       "version" : "0.3-pre"
    }
}
```

**Comment by AArnott** [comment]
Sure. I'd accept that PR.
