### ISSUE TITLE
Projects using this fail to compile under Pop_OS

### ISSUE THREAD

**Issue by ZoeyR** [dotnet/Nerdbank.GitVersioning#490]
When compiling on Pop_OS (The ubuntu derivative used on system76 laptops) the following exception occurs:

System.PlatformNotSupportedException: pop.20.04-x64

**Comment by AArnott** [comment]
Duplicate of #482. In particular notice this comment: https://github.com/dotnet/Nerdbank.GitVersioning/issues/482#issuecomment-633728078
