### ISSUE TITLE
there is a hole in the bucket dear lisa....

### ISSUE THREAD

**Issue by dszryan** [dotnet/Nerdbank.GitVersioning#491]
trying to get to the bottom of the issue here: https://github.com/dotnet/Nerdbank.GitVersioning/issues/433
and noticed the platform error `System.PlatformNotSupportedException: arch-x64` (My platform Arch Linux is not supported)

so decide to [libgit2sharp](https://github.com/libgit2/libgit2sharp) up and running..

but that uses [Nerdbank.GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning) for its build...

which does not build since it uses ... you see where I am going with this... [There's a Hole in the Bucket](https://www.youtube.com/watch?v=yD-ffhvefsw)

**Comment by AArnott** [comment]
You can hopefully plug the hole there by removing nb.gv from the package references in libgit2sharp when building it locally, since *most* nb.gv users don't have any compile-time dependency on nb.gv. Or build libgit2sharp on a supported linux distro, and then copy it to the arch linux distro you're testing on to see if whatever fix you're preparing works.

**Comment by AArnott** [comment]
Thanks for looking into this, BTW. I haven't had time to chase down all the linux distros that people are using. We support several, but until libgit2sharp removes the native dependency on libssl, it's always going to be a constant effort to support the next popular distro.

**Comment by dszryan** [comment]
yeah, did end up removing nb.gv from libgit2sharp dependency, raised the ticket to highlight the obvious cyclic dependency.

> You can hopefully plug the hole there by removing nb.gv from the package references in libgit2sharp when building it locally, since _most_ nb.gv users don't have any compile-time dependency on nb.gv. Or build libgit2sharp on a supported linux distro, and then copy it to the arch linux distro you're testing on to see if whatever fix you're preparing works.
