### ISSUE TITLE
Correct way to override versioning in csproj?

### ISSUE THREAD

**Issue by pergardebrink** [dotnet/Nerdbank.GitVersioning#495]
For legacy reasons, I need to set the AssemblyInformationalVersion to a specific fixed string + the version as the
NuGetPackageVersion produces (actually, I need SemVer2 from the VersionOracle, but cannot access it from csproj?). 

The solution I have is currently looks something like this and I was wondering if it's the correct way to do it, or if there's a better way?:

**Directory.Build.props:**
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning">
            <Version>3.2.31</Version>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <Target Name="AdjustVersion" DependsOnTargets="GetBuildVersion" AfterTargets="GetBuildVersion">
        <PropertyGroup>
            <AssemblyInformationalVersion>release/v$(NuGetPackageVersion)</AssemblyInformationalVersion>
        </PropertyGroup>
    </Target>

</Project>
```

**Comment by AArnott** [comment]
Yup. That's a great way to do it.

**Comment by pergardebrink** [comment]
Thanks!

**Comment by medianick** [comment]
I discovered this same `AfterTargets="GetBuildVersion"` technique today. We needed to be able to customize the version utilized by a NuGet pack (automatic, triggered by the GeneratePackageOnBuild property), but to have it generate unique, _incrementing_ version numbers (using the git height) for a public release branch. E.g., for every build of branch 1.2.3, we needed to package 1.2.3.1, then 1.2.3.2, etc.

Overriding the PackageVersion with the AssemblyVersion via this technique was the only way we found to do it. Before doing this, every new build of branch 1.2.3 created package 1.2.3.

**Comment by AArnott** [comment]
@medianick  thanks for sharing. It sounds like you may be interested in #719.

**Comment by silkfire** [comment]
@medianick What did you use to calculate the incremented version number?

**Comment by medianick** [comment]
> @medianick What did you use to calculate the incremented version number?

@silkfire it looks like this:

```json
  "version": "1.2.3",
  "nuGetPackageVersion": {
    "precision": "revision"
  },
```

This generates 1.2.3.1, 1.2.3.2, etc.
