### ISSUE TITLE
Using a soon to be deprecated GitHub Actions feature

### ISSUE THREAD

**Issue by tevoinea** [dotnet/Nerdbank.GitVersioning#517]
GitHub Actions is deprecating the `set-env` and `add-path` commands. More details here: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

This project uses `set-env` here: https://github.com/dotnet/Nerdbank.GitVersioning/blob/57a48267cb748f0e1469bd1b346e23932f8cfe9b/azure-pipelines/Set-EnvVars.ps1#L48-L50

and `add-path` here:
https://github.com/dotnet/Nerdbank.GitVersioning/blob/57a48267cb748f0e1469bd1b346e23932f8cfe9b/azure-pipelines/Set-EnvVars.ps1#L73-L75

Right now this is causing warnings in all of our workflows that use `dotnet` and it looks like the Actions team is planning to disable the commands in the future.

The fix seems to be relatively small/easy (the only usages I found were quoted above), if that's the case I'm also happy to open a PR with the fix 😊

**Comment by AArnott** [comment]
Already fixed by #516
