### ISSUE TITLE
nbgv install adds PackageReference even to vcxproj projects, which breaks their build

### ISSUE THREAD

**Issue by tmilnthorp** [dotnet/Nerdbank.GitVersioning#533]
Hello,

I have a solution that contains some C++/Cli projects, and doing a ```ngbv install``` breaks ```nuget restore``` when run from the command line.
```
##[error]The nuget command failed with exit code(1) and error(NU1201: Project MyCliProject is not compatible with net462 (.NETFramework,Version=v4.6.2). Project MyCliProject  supports: native (native,Version=v0.0)
```

The issue is that Directory.Build.props adds a ProjectReference for all project types. This fails as the project type is technically "native" for C++/Cli.

I found I can fix this issue my adding a condition to the PackageReference ItemGroup:
```xml
  <ItemGroup Condition="'$(PlatformToolset)' == ''">
    <PackageReference Include="Nerdbank.GitVersioning">
      <Version>3.3.37</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```

This works since C# projects do not define a PlatformToolset as the C++/Cli projects do.

I would create a PR, but I am unsure if this is a generic enough fix for all supported project types. Your thoughts?

Tristan

**Comment by AArnott** [comment]
Thanks for the report and the suggested workaround.
Actually though, we do expect this package to work for C++ projects so I'm surprised to see this failure. NB.GV actually creates version.rc files for C++ binaries.
Can you perhaps create a minimal repro and share?

**Comment by tmilnthorp** [comment]
Sure, you can access a bare-bones repo [here](https://github.com/tmilnthorp/CppCliFailureNBGC).

If you clone, simply do a ```nuget retore CppCliFailureNBGC.sln```

It will appear to succeed, however you'll note boost (which is installed in packages.config) isn't downloaded. Note that packages.config is the only option supported by C++/Cli projects since they are "native" targets.

Perhaps we can key off
```xml
<CLRSupport>true</CLRSupport>
```

I believe this value can also be netcore for some C++/Cli projects.

**Comment by tmilnthorp** [comment]
Thanks for the quick fix! Unfortunately, I've uncovered more. I've pushed new code to the [same repository](https://github.com/tmilnthorp/CppCliFailureNBGC). 

```nuget retore CppCliFailureNBGC.sln``` still fails even when there's just a .NET Framework class library.

It appears this occurs when any project is utilizing the packages.config NuGet style.

Some of my C# projects contain the following at the bottom, which has a ```EnsureNuGetPackageBuildImports``` target.
```xml
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\MSTest.TestAdapter.2.1.0\build\net45\MSTest.TestAdapter.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\MSTest.TestAdapter.2.1.0\build\net45\MSTest.TestAdapter.props'))" />
    <Error Condition="!Exists('..\packages\MSTest.TestAdapter.2.1.0\build\net45\MSTest.TestAdapter.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\MSTest.TestAdapter.2.1.0\build\net45\MSTest.TestAdapter.targets'))" />
  </Target>
  <Import Project="..\packages\MSTest.TestAdapter.2.1.0\build\net45\MSTest.TestAdapter.targets" Condition="Exists('..\packages\MSTest.TestAdapter.2.1.0\build\net45\MSTest.TestAdapter.targets')" />
```

However the project I pushed does not have this, while still utilizing packages.config. Perhaps this changed with a recent version of Visual Studio? In any case, I'm not sure how we can have the ProjectReference excluded from any project that utilizes packages.config.

**Comment by tmilnthorp** [comment]
I found this has fixed it and avoids intermixing PackageReferences when packages.config is used (C++/Cli, C#, or otherwise).

```xml
  <ItemGroup Condition="!Exists('packages.config')">
    <PackageReference Include="Nerdbank.GitVersioning">
      <Version>3.3.37</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```

**Comment by AArnott** [comment]
Thanks. I suppose we should combine this with the previous condition you suggested earlier so that it doesn't break vcxproj builds that don't have a packages.config file either, right?

**Comment by tmilnthorp** [comment]
Actually, I don't believe so.

It only happens when mixing the PackageReference and packages.config styles in a project, whether it be C#, C++/Cli, or native C++. According to [this](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files), PackageReference isn't supported on JavaScript and certain ASP.NET projects either. This should fix those cases also, although I have no experience with those types.

Checking for packages.config should be all that's necessary, at least for the nuget restore.

**Comment by tmilnthorp** [comment]
I tried the ``` Condition="!Exists('packages.config')"``` version in a few large solutions which have a mix of C++, C++/Cli, and C# and it worked well.

**Comment by AArnott** [comment]
I've changed the PR to just that new simple condition then. Thank you.
