### ISSUE TITLE
nbgv does not update the version in Directory.Build.props

### ISSUE THREAD

**Issue by BobVul** [dotnet/Nerdbank.GitVersioning#537]
The [documentation](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/nbgv-cli.md) states:

> It will also add/modify your `Directory.Build.props` file in the root of your repo to add the `PackageReference` to the latest `Nerdbank.GitVersioning` package available on nuget.org.

However, running `nbgv install` does not appear to update the PackageReference. It stays at the old version. If I first delete `Directory.Build.props`, then `nbgv install` will create a new one with the updated version. The same behaviour occurs in nbgv 3.2.31 and 3.3.37 (`dotnet tool update -g nbgv`).

```
PM> cat .\Directory.Build.props
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning">
      <Version>3.2.31</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
PM> nbgv install
PM> cat .\Directory.Build.props
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning">
      <Version>3.2.31</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
PM> rm .\Directory.Build.props
PM> nbgv install
PM> cat .\Directory.Build.props
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning">
      <Version>3.3.37</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

**Comment by AArnott** [comment]
Thanks for the report, @BobVul

**Comment by NArnott** [comment]
Just came across this as well. And not only did it _not_ update the props file, but it also _overrode_ the version set in the version.json file back to "1.0-beta"

**Comment by AArnott** [comment]
`nbgv install` was never meant to be a maintenance command. It was just supposed to install nb.gv to a repo that didn't use it before. It's smart enough to avoid adding a redundant PackageReference, but not smart enough to avoid stomping on version.json, apparently.
If someone wants to send a PR to enhance it, I'll be happy to take it.
