### ISSUE TITLE
PathFilter behaviors

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/Nerdbank.GitVersioning#551]
I try to understand how path filter behave in version.json files with inherited set to true. From what I observed up to now is, if I set the PathFilter in the root version.json to "." then the versions of all projects will be bumped up, no matter what I define there as a PathFilter. When I remove the PathFilter from the root version.json and set it only on the projects' version.json files they bump up independently from each other. 
What makes me wonder is that the calculated git height keep the value it had before I moved the PathFilter setting down to the projects level is kept. I would expect that I get then another calculated git height, because of the different scope.  So, somehow it seems that gitversioning has a invisible caching or persistency. 

In the docs I didn't find anything related to the git height bump up logic. Can you tell me how the bumping works and where gitversioning stores additional data?

**Comment by AArnott** [comment]
The git height calculation strives to never go backward, as that would lead to regressing version numbers. So when you add a commit that moves the path filter to a lower place, _future_ commits will honor that new setting, but past commits will continue to honor the settings as defined in those commits.
So NB.GV isn't keeping an invisible cache anywhere. It is git history itself, and the algorithm that each commit should only ever *add* 1 to the calculated height (or add 0, if the path filter excludes all the paths that were changed by that commit).
