### ISSUE TITLE
WorkTree With managed Git

### ISSUE THREAD

**Issue by bsagal** [dotnet/Nerdbank.GitVersioning#553]
When runing `nbgv get-version` (with nbgv version v3.4.161-alpha+a44c1fae2a) in my git worktree i get the following error

    ERROR: The commit 0000000000000000000000000000000000000000 was not found in this repository.

When falling back to LibGit2 it works as expected

**Comment by AArnott** [comment]
I can confirm. Thank you for identifying this regression.
