### ISSUE TITLE
How can I specify the format of the generated version? 

### ISSUE THREAD

**Issue by Summpot** [dotnet/Nerdbank.GitVersioning#558]
For example, the version.json in my repository looks like this.
``` json
{
  "$schema": "...",
  "version": "2.276.1",
  "publicReleaseRefSpec": [
    "^refs/heads/master$",
    "^refs/heads/v\\d+(?:\\.\\d+)?$"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
      
    }
  }
}
```
Then nbgv generated the following version information.
``` csharp
    internal const string AssemblyVersion = "2.276.0.0";
    internal const string AssemblyFileVersion = "2.276.3.1";
    internal const string AssemblyInformationalVersion = "2.276.3+1148553a20";
```
Among them, the 0 at the end of the `AssemblyVersion` is not needed, how can I remove them.

Thank you very much.
@AArnott

**Comment by AArnott** [comment]
Actually the 0's at the end of assembly version are needed to match the actual assembly version, which *always* has 4 components to it. This constant is emitted to help you assemble an `AssemblyName`, among other things, and the AssemblyName would expect 4 parts.

**Comment by Summpot** [comment]
I want to use nbgv in a project that has already released releases. The previous version numbers are three parts. Is there really no other way? Thank you very much.
