### ISSUE TITLE
Auto-completions do not work

### ISSUE THREAD

**Issue by heaths** [dotnet/Nerdbank.GitVersioning#559]
Using nbgv v3.3.37+0989e8fe0c

It seems middleware for `System.CommandLine` like `[parse]` and `[debug]` do not work, thus breaking [autocompleters in bash, PowerShel, etc.](https://github.com/dotnet/command-line-api/blob/main/docs/dotnet-suggest.md)

For example,
```powershell
dotnet-suggest get -e C:\Users\username\.dotnet\tools\nbgv.exe --position 5 -- nbgv
```
```text
error: unknown command '[suggest:0]'
nbgv v3.3.37+0989e8fe0c
Use -h, --help, or -? for usage help. Use after a command to get more help about a particular command.
```

Another example:
```powershell
nbgv [parse] --foo
```
```text
nbgv v3.3.37+0989e8fe0c
Use -h, --help, or -? for usage help. Use after a command to get more help about a particular command.
error: unknown command '[parse]'
```

This should have printed the tokens, and is what `dotnet-suggest` seems to use to provide completions automatically. For example:

```powershell
dotnet-suggest [parse] get -e foo -p bar
```
```text
[ dotnet-suggest [ get [ -e <foo> ] [ -p !<bar> ] ] ]
```

**Comment by AArnott** [comment]
I saw that feature advertised recently too. I tried it on a new tool I wrote and it didn't work there either.
I don't expect it to work on nbgv because it uses a very old version of the System.CommandLine library. But the new tool I wrote used the latest one and still failed. So IMO this is a non-goal until I see it working _somewhere_.

**Comment by heaths** [comment]
It works great for me across a myriad of tools, including dotnet-suggest, dotnet-trace, dotnet-format, coverlet.console, and more. nbgv is the only one I have installed that doesn't.

Please open the bug back up and I can upgrade to a newer System.CommandLine if you want. I use it across my projects frequently.

**Comment by heaths** [comment]
...and if you explain how you tried it and it didn't work for you, I can probably suggest what you could try instead. For example, if modifying your PowerShell `$profile` per instructions, you either need to start a new PowerShell source or re-dotsource your `$profile`.

**Comment by heaths** [comment]
See below. Note, also, that for `dotnet-*` tools you have to use `dotnet-<name>` instead of `dotnet name` because the autocompleter is registered to the application name, which is `dotnet-<name>`.

https://user-images.githubusercontent.com/1532486/108290899-2b1e7d80-7146-11eb-813c-9e721a5df9f2.mp4
