### ISSUE TITLE
Regression - 3.4.190 no longer works with submodule

### ISSUE THREAD

**Issue by mhutch** [dotnet/Nerdbank.GitVersioning#578]
I have a project that does not use GitVersioning itself, but submodules a project that uses GitVersioning. Using 3.4.190, it fails with an internal error "No git repo found here": 

```
error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
error MSB4018: System.ArgumentException: No git repo found here. (Parameter 'workingDirectory')
error MSB4018:    at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
```
I found that 3.3.37 works fine, so I used that and created a GitHub Action PR demonstrating that 3.3.37->3.4.190 upgrade breaks:

https://github.com/mhutch/MonoDevelop.Xml/actions/runs/724957601

**Comment by AArnott** [comment]
Thanks for reporting. I'll investigate. In the meantime, you have two workarounds:

1. Pin an older version of NB.GV to use
2. Switch 3.4 back to the libgit2 engine as described in [the release notes](https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.4.142-alpha).
