### ISSUE TITLE
GIT alternates not supported with version 3.4x

### ISSUE THREAD

**Issue by Sam13** [dotnet/Nerdbank.GitVersioning#595]
When repository is checked out with GIT alternates (e.g. as TeamCity does) NBGV get-version fails:
`Nerdbank.GitVersioning.GitException: An commit object with SHA 163380e3fa79d36c0e51efc251132aa7e7f86b9d could not be found.`

To reproduce:
_git clone --mirror https://github.com/dotnet/Nerdbank.GitVersioning.git_
_git clone --shared --reference .\Nerdbank.GitVersioning.git https://github.com/dotnet/Nerdbank.GitVersioning.git test_
_cd test_
_nbgv Get-Version_

I'm using NBGV v3.4.194 on Windows.
Setting _NBGV_GitEngine=LibGit2_ works but unfortunately not in Docker image _mcr.microsoft.com/dotnet/sdk:5.0_ because of dependency load problems for LibGit2.

**Comment by AArnott** [comment]
It looks like yet another storage variance with git that our new managed implementation may not yet support?
@qmfrederik what do you think?

**Comment by qmfrederik** [comment]
There was some work done to support alternates, e.g. https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/src/NerdBank.GitVersioning/ManagedGit/GitRepository.cs#L537-L568 (and in the constructor), but obviously it fails here.

I'll try to free up some time to have a look at the open managed-git issues (this one seems easy to reproduce). (Unfortunately, freeing up time is not so easy lately).

**Comment by AArnott** [comment]
> Unfortunately, freeing up time is not so easy lately

Understandable. I _really_ appreciate how responsive you've been and how well you're supporting your new feature. We don't hear a lot about folks unblocked in 3.4 on various linux distros as a result of your work, but I assume that's because people mostly give feedback when something's broken rather than when it works. And I used to get a stream of complaints about various distros, and I haven't heard a peep since your work, so that's great! 
@Sam13 even mentioned the libgit2 workaround doesn't work for him because he is in a linux environment where it doesn't work, so clearly your new feature is having a positive impact.

**Comment by qmfrederik** [comment]
Thanks, @AArnott . I had a look at two issues which seemed straightforward (including this one). Issues like #584 and #587 will probably need more time. Do you think you could label issues related to the managed git implementation with a managed-git label or something similar? That would help me identify those.

**Comment by qmfrederik** [comment]
@AArnott By the way, [from a conversation on another project](https://github.com/DiscUtils/DiscUtils/issues/232#issuecomment-829200375):

> As long as there is no native dependency (that's bugged me a lot), and that it's fast.. One issue I had with one of the gitversion tools was that it recalculated the version for each project in a solution (hence my tendency to calculate versioning once and apply it by includes).. Minver has yet to show the same slowness.

Performance and portability seem to be a common concern for users of git-based versioning tools in the ecosystem. Glad to see nbgv making progress on both fronts!

**Comment by AArnott** [comment]
@Sam13 would you be willing to test @qmfrederik's fix to see if it resolves your issue?

Use version 3.4.201 from here: https://dev.azure.com/andrewarnott/OSS/_packaging?_a=package&feed=PublicCI&package=Nerdbank.GitVersioning&protocolType=NuGet&version=3.4.201&view=overview

Thanks.

**Comment by Sam13** [comment]
Still fails on Teamcity (which is using alternates):
```
/root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
  /root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: Nerdbank.GitVersioning.GitException: An commit object with SHA b34230dc4f18514928ead73604be154c9a1d57d4 could not be found.
  /root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetObjectBySha(GitObjectId sha, String objectType)
  /root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetCommit(GitObjectId sha, Boolean readAuthor)
  /root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetHeadCommit(Boolean readAuthor)
  /root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
  /root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
  /root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
```

When running without alternates https://github.com/dotnet/Nerdbank.GitVersioning/issues/587 happens

**Comment by qmfrederik** [comment]
@Sam13 Thanks for testing! Could you share the contents of the alternates file on the Teamcity server?

**Comment by Sam13** [comment]
The content looks like that:
```
C:\TeamCity\BuildAgent\system\git\git-0E4C94A5.git\objects
```

**Comment by qmfrederik** [comment]
@Sam13 Hmm, now you got me confused - the TeamCity build log shows:

```
/root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
```

which made me think that was a Linux server, but `C:\TeamCity\BuildAgent\system\git\git-0E4C94A5.git\objects` is a Windows path.

Is this running WSL or something similar?

**Comment by Sam13** [comment]
Sorry for the confusion.
This happens if your Build Agent is on Windows and you're running Linux containers.
If the build agent is Linux the content of the alternate files looks like that:
`/teamcity/system/git/git-84BA29EB.git/objects`

**Comment by qmfrederik** [comment]
@Sam13 I have to admit don't know much about WSL2 (assuming that's how you run your containers).

I didn't expect a Windows-style path inside a Linux environment. Does `git show b34230dc4f18514928ead73604be154c9a1d57d4` work if you run that command inside a container?

**Comment by Sam13** [comment]
@qmfrederik I did some more investigation by executing the following commands in my containers:
```
GIT_ALTERNATES_PATH=$$(cat .git/objects/info/alternates) &&
echo $$GIT_ALTERNATES_PATH &&
ls $$GIT_ALTERNATES_PATH &&
git log -n 1
```                      

When I run this on a Linux host, Linux container GIT log shows commit information but NBGV fails:
```                      
/root/.nuget/packages/nerdbank.gitversioning/3.4.201/build/Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: Nerdbank.GitVersioning.GitException: An commit object with SHA 4a25bea23766ed23f5763b03fdaa1cded6734e3f could not be found.
```

When I run this on a Windows host, Linux container NBGV 3.4.201 works. (Altough GIT log fails)

So for me it seems that NBGV 3.4.201 seems to fail only on Linux?

**Comment by qmfrederik** [comment]
> When I run this on a Linux host

Can you copy the output of `echo $$GIT_ALTERNATES_PATH`?

**Comment by Sam13** [comment]
> 
> Can you copy the output of `echo $$GIT_ALTERNATES_PATH`?

`/teamcity/system/git/git-84BA29EB.git/objects`

**Comment by qmfrederik** [comment]
@Sam13  Thanks, do you know whether there's a trailing `\n` character at the end?

**Comment by Sam13** [comment]
@qmfrederik Prerelease v3.4.203 works on Linux host with Linux container!

Altough GIT height is always zero (https://github.com/dotnet/Nerdbank.GitVersioning/issues/587)

**Comment by 3x0dv5** [comment]
Hi guys,
using github actions I see this problem happening, here is a job that fails with this error:
https://github.com/ruilimacom/amiliur.annotations/actions/runs/4823851800/jobs/8592878009

**Comment by AArnott** [comment]
@3x0dv5 Your fetch-depth is 1: https://github.com/ruilimacom/amiliur.annotations/actions/runs/4823851800/jobs/8592878009#step:2:8

You need to set fetch-depth to 0 so that history is downloaded.
