### ISSUE TITLE
Add cake-addin tag to Cake.GitVersioning NuGet package

### ISSUE THREAD

**Issue by augustoproiete** [dotnet/Nerdbank.GitVersioning#604]
The [NuGet Gallery](https://nuget.org) now includes a "Cake" tab with instructions on how to use NuGet packages in Cake build scripts.

The instructions shown can be tailored based on the presence of specific tags in the NuGet package.

I'd like to suggest that the tag `cake-addin` be included in the NuGet package of Cake.GitVersioning, so that the NuGet Gallery can display the instructions to install this addin using the `#addin` directive.

Once the `cake-addin` tag is added and a new version of the NuGet package is published, the UI will look similar to this:

![image](https://user-images.githubusercontent.com/177608/119424704-52a05b80-bcdc-11eb-9291-57b1b9e208de.png)

This is also documented in best practices on tags for Cake addins: https://cakebuild.net/docs/extending/addins/best-practices#tags

ps: Happy to send a PR

**Comment by AArnott** [comment]
Sounds good.
