### ISSUE TITLE
Update Cake.GitVersioning NuGet package icon

### ISSUE THREAD

**Issue by augustoproiete** [dotnet/Nerdbank.GitVersioning#605]
We've recently released new icons for Cake extensions, to help more easily differentiate Cake Addins, Modules, Recipes, etc.

[![cake-contrib logos](https://user-images.githubusercontent.com/177608/116633858-f5a9c380-a930-11eb-8333-e5cd978e3340.png)](https://github.com/cake-contrib/graphics)

I'd like to suggest updating the icon of the Cake.GitVersioning NuGet package to the new icon for Cake addins: `https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/addin/cake-contrib-addin-medium.png`

![cake-addin](https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/addin/cake-contrib-addin-medium.png)

More information: https://github.com/cake-contrib/graphics

ps: Happy to send a PR

**Comment by AArnott** [comment]
Sure. We'll take a PR.

**Comment by KalleOlaviNiemitalo** [comment]
I guess the icon will need to be listed in ThirdPartyNotices <https://github.com/dotnet/Nerdbank.GitVersioning/issues/593> as well.
