### ISSUE TITLE
nbgv prepare-release does not update Directory.Build.props

### ISSUE THREAD

**Issue by sikri-eic** [dotnet/Nerdbank.GitVersioning#610]
I have a project structure where my `Directory.Build.props` file (which sets `VersionPrefix` and `VersionSuffix`) is under directory `Source`. When I `nbgv install` in my repo, it creates another `Directory.Build.props` at the root of my repository (which is fine by me). But when I run `nbgv prepare-release` I see that my `Directory.Build.props` file remains untouched. In fact, both of the *props files remain untouched. I was expecting nbgv to update at least one of the `Directory.Build.props` files with the new version. I suppose I'm doing something wrong? Is nbgv compatible with `Directory.Build.props`? If so, what is the proper way to use it with `Directory.Build.props`?

(BTW: I tried running `nbgv install` under `Source` directory, but that still created the `version.json` file at repository root).

**Comment by AArnott** [comment]
Using `VersionSuffix` and such properties is not supported. All version information should be set in `version.json`.

**Comment by sikri-eic** [comment]
Thank you for the response. I hope it would one day be possible :)
