### ISSUE TITLE
Project specific version

### ISSUE THREAD

**Issue by dansiegel** [dotnet/Nerdbank.GitVersioning#612]
# Description

I have several projects where I am looking to add support for Maui. Obviously it'll be a while before Maui itself is really stable and in the mean time I would prefer to keep the rest of the library publishing as X.X where I would like to have the Maui support packages published as prerelease packages. It would be great if we could somehow achieve this so I end up with:

MyPackage.Forms.2.0.0.nupkg
MyPackage.Maui.2.0.0-pre.nupkg

**Comment by AArnott** [comment]
You can indeed. You can add a `version.json` file to the Maui directory with `inherit: true` set and the version you want to use there.

**Comment by dansiegel** [comment]
thanks @AArnott I did not even know that was an option!
