### ISSUE TITLE
Versions after v3.3.37 doesn't work on Windows 7

### ISSUE THREAD

**Issue by fehrm** [dotnet/Nerdbank.GitVersioning#615]
With version after v3.3.37, NBGV fails when doing a simple dotnet build in new repo.

Error is as follows:
>error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
error MSB4018: System.EntryPointNotFoundException: Unable to find an entry point named 'CreateFile' in DLL 'api-ms-win-core-file-l1-2-0.dll'.
error MSB4018:    at PInvoke.Kernel32.CreateFile(Char* filename, ACCESS_MASK access, FileShare share, SECURITY_ATTRIBUTES* securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
error MSB4018:    at PInvoke.Kernel32.CreateFile(String filename, ACCESS_MASK access, FileShare share, SECURITY_ATTRIBUTES* securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
error MSB4018:    at PInvoke.Kernel32.CreateFile(String filename, ACCESS_MASK access, FileShare share, Nullable`1 securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.FileHelpers.TryOpen(String path, FileStream& stream)
error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository..ctor(String workingDirectory, String gitDirectory, String commonDirectory, String objectDirectory)
error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.Create(String workingDirectory)
error MSB4018:    at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()

For full error, see last step.

Running command ```ver``` on my machine
> Microsoft Windows [Version 6.1.7601]

Steps to reproduce
1. dotnet --version
> 3.1.410
2. dotnet new console
3. git init
4. git add -A && git commit -m "init"
5. dotnet tool install -g nbgv
5. nbgv install
6. git add -A && git commit -m "nbgv"
7. dotnet build

> Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
>
>  Determining projects to restore...
>  All projects are up-to-date for restore.
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.EntryPointNotFoundException: Unable to find an entry point named 'CreateFile' in DLL 'api-ms-win-core-file-l1-2-0.dll'.
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at PInvoke.Kernel32.CreateFile(Char* filename, ACCESS_MASK access, FileShare share, SECURITY_ATTRIBUTES* securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at PInvoke.Kernel32.CreateFile(String filename, ACCESS_MASK access, FileShare share, SECURITY_ATTRIBUTES* securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at PInvoke.Kernel32.CreateFile(String filename, ACCESS_MASK access, FileShare share, Nullable`1 securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.FileHelpers.TryOpen(String path, FileStream& stream)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository..ctor(String workingDirectory, String gitDirectory, String commonDirectory, String objectDirectory)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.Create(String workingDirectory)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
>
>Build FAILED.
>
>C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.EntryPointNotFoundException: Unable to find an entry point named 'CreateFile' in DLL 'api-ms-win-core-file-l1-2-0.dll'.
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at PInvoke.Kernel32.CreateFile(Char* filename, ACCESS_MASK access, FileShare share, SECURITY_ATTRIBUTES* securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at PInvoke.Kernel32.CreateFile(String filename, ACCESS_MASK access, FileShare share, SECURITY_ATTRIBUTES* securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at PInvoke.Kernel32.CreateFile(String filename, ACCESS_MASK access, FileShare share, Nullable`1 securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.FileHelpers.TryOpen(String path, FileStream& stream)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository..ctor(String workingDirectory, String gitDirectory, String commonDirectory, String objectDirectory)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.ManagedGit.GitRepository.Create(String workingDirectory)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.205\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
>    0 Warning(s)
    1 Error(s)
>
>Time Elapsed 00:00:01.14
>

**Comment by AArnott** [comment]
Would you be willing to test the fix, which you can download from the build artifact in #616's PR build?

**Comment by AArnott** [comment]
I guess that invitation was a bit premature. The PR build failed. I'll work on it.

**Comment by fehrm** [comment]
First, thanks for answering so quickly.

I'll gladly test it when it is ready!

**Comment by AArnott** [comment]
Ok, it's ready for testing from here: https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=4813&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by fehrm** [comment]
Worked first try, added it as a local NuGet package for same Console project and made sure it was being used:

1. dotnet build -v d 
> [...]
>      2>Target "GetBuildVersionCore" in project "C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.217-gbfab409102\build\Nerdbank.GitVersioning.Inner.targets" (target "GetBuildVersion_Properties" depends on it):
       Using "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task from assembly "C:\Users\user\\.nuget\packages\nerdbank.gitversioning\3.4.217-gbfab409102\build\MSBuildCore/Nerdbank.GitVersioning.Tasks.dll".
       Task "Nerdbank.GitVersioning.Tasks.GetBuildVersion"
       Done executing task "Nerdbank.GitVersioning.Tasks.GetBuildVersion".
> [...]
>
> Build succeeded.
> 0 Warning(s)
> 0 Error(s)

Amazing, thanks!

**Comment by AArnott** [comment]
Thanks for verifying!
