### ISSUE TITLE
nbgv get-version NuGetPackageVersion suddenly not working

### ISSUE THREAD

**Issue by edwardskrod** [dotnet/Nerdbank.GitVersioning#623]
Hi folks!  Normally, when I run nbgv get-version (with the version set to 0.0.0.12), the NuGetPackageVersion would be something like this:

0.0.0-gdd2f369885

However, as of this morning, it's been returning this:  0.0.0

D:\project>nbgv get-version
Version:                      0.0.0.12
AssemblyVersion:              0.0.0.0
AssemblyInformationalVersion: 0.0.0+8d12f371d4
NuGetPackageVersion:          0.0.0
NpmPackageVersion:            0.0.0

Here's my version.json:

```
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.0.0.12",
  "publicReleaseRefSpec": [
    "^refs/heads/main$"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": false
    }
  }
}
```

This has messed up our Azure Pipeline.  Any help would be apprecaited.

**Comment by AArnott** [comment]
Can you tell us the `nbgv` version you used when it worked and the first version where it broke?

**Comment by edwardskrod** [comment]
Here's the version I have on my machine:  nbgv v3.4.194+8126d95e2c

**Comment by edwardskrod** [comment]
I don't think I changed versions.  That's what's so strange.  What could be a reason that it wouldn't work?

**Comment by edwardskrod** [comment]
On the pipeline, here's a version it didn't work:  Tool 'nbgv' (version '3.4.203') was successfully installed.

Here's one where it did work. 
Tool 'nbgv' (version '3.4.203') was successfully installed.


So it looks like it's working and failing with the same version.

**Comment by edwardskrod** [comment]
When I push a PR to main, and then try to run the Azure Pipeline with nbgv against Main, I wonder if that has something to do with this.

Because once I commit, then run the tool, the get-version returns correct:

nbgv get-version -v NuGetPackageVersion
0.0.0-g7a4be5c8d9

**Comment by AArnott** [comment]
> Because once I commit

Once you commit what? What do you change in the commit that makes it start or stop working?

**Comment by edwardskrod** [comment]
When I create a topic branch off of main, change the version, then commit the change, the value is set correctly.

But when I try to execute the Azure Pipeline, the value is not set properly.   

I wonder if it's because there isn't a specific commit associated with it.  I really don't know.  But it seems like I'm doing something wrong.  

https://devdiv.visualstudio.com/DevDiv/_build?definitionId=14485&_a=summary
