### ISSUE TITLE
Q: `nbgv prepare-release` for versions older than `master`

### ISSUE THREAD

**Issue by alexrp** [dotnet/Nerdbank.GitVersioning#628]
Hi,

My situation is this: On `master`, development for 2.0 is ongoing, so version is set to `2.0-dev`. I have a `release/v1.0` branch (created with `nbgv prepare-release`) from which I've released a few 1.0.z versions. Somewhere along the lines, I decided I want to do a 1.1 release with a couple of the feature additions that would have gone into 2.0 as these additions aren't breaking, and I want users to be able to get those features without committing to a 2.0 upgrade that involves dealing with other breaking changes.

My question is: What's the expected workflow for a situation like this? My first thought was to do `nbgv prepare-release` from `release/v1.0`, but that just turns into a no-op with the message `release/v1.0 branch advanced from 1.0 to 1.0` (passing `--nextVersion 1.1` or `--versionIncrement Minor` makes no difference).

**Comment by AArnott** [comment]
I would create a `v1.1` branch, based on your `release/v1.0` branch and do your development there. 
You could either modify `version.json` directly or use `nbgv set-version 1.1-beta` in that branch to set the version to 1.1.

**Comment by alexrp** [comment]
Makes sense. Thanks!
