### ISSUE TITLE
Branch policy for version increment

### ISSUE THREAD

**Issue by xperiandri** [dotnet/Nerdbank.GitVersioning#640]
Is it possible to set branch policy on Azure DevOps that do not allow to merge from develop to main/master if a version is not incremented in `version.json` since the last commit to main/master?

**Comment by AArnott** [comment]
I don't think so. Unless there's an AzDO extensibility point that lets you upload custom policies.

**Comment by xperiandri** [comment]
I can check build results before a merge. For example, code coverage. But it must be published after build
