### ISSUE TITLE
Version height calculated differently in 3.4 with new git backend

### ISSUE THREAD

**Issue by nmeyering** [dotnet/Nerdbank.GitVersioning#658]
It seems git version height still yields different results with the new git backend in some cases. This tripped us up because it meant old packages were being overwritten with new ones, causing chaos in our dependency graph.

Seems to be different from #587 since we get a non-zero version and it still happens in `3.4.231`?

```
$ dotnet tool install --global nbgv
You can invoke the tool using the following command: nbgv
Tool 'nbgv' (version '3.4.231') was successfully installed.
$ nbgv.exe get-version
Version:                      1.0.28.5486
AssemblyVersion:              1.0.0.0
AssemblyInformationalVersion: 1.0.28+6e152011
NuGetPackageVersion:          1.0.28
NpmPackageVersion:            1.0.28
```

and with the old git backend:

```
$ NBGV_GitEngine=LibGit2 nbgv.exe get-version
Version:                      1.0.49.5486
AssemblyVersion:              1.0.0.0
AssemblyInformationalVersion: 1.0.49+6e152011
NuGetPackageVersion:          1.0.49
NpmPackageVersion:            1.0.49
```

Nbgv version 3.3.37 yields `1.0.49` also.

The `version.json` file is:
```
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.0",
  "pathFilters": ["."],
  "gitCommitIdShortFixedLength": 8,
  "publicReleaseRefSpec": [
    "^refs/heads/develop$"
  ]
}
```

**Comment by AArnott** [comment]
Ooh, that doesn't sound good. Sorry about the package version overwriting. That sounds terrible.

Can you share your git history / repo so we can use it to study the problem? 
What level in your repo is your version.json file found in? Can you tell me about its history, including how long path filters have been in there? Do other version.json files exist in your repo or in the past?

**Comment by nmeyering** [comment]
Hey thanks for the quick reply.

Sorry, I can't share the repo itself, but I'll try to give as much context as possible.
The version.json file is two levels deep at the root of its dotnet project (next to the `.csproj` file): `Repository/src/Project/version.json` while `Repository/.git` is the git dir location.
The version.json only has one commit in its history and it's the same commit that also introduced the whole `src/Project` dir. So therefore the same path filter has always been there.

**Comment by nmeyering** [comment]
Ok I took the time and thankfully it was fairly easy to reproduce. All you apparently need is a merge commit with relevant changes in both parents.

If you clone this repo: https://github.com/nmeyering/nbgv-bug-repro

and run

```
$ nbgv get-version -v VersionHeight; NBGV_GitEngine=LibGit2 nbgv get-version -v VersionHeight
2
3
```

you should see the output differs.
