### ISSUE TITLE
Shipping ManagedGit as a separate package

### ISSUE THREAD

**Issue by GlebChili** [dotnet/Nerdbank.GitVersioning#680]
Hi!

Are there any plans to ship your ManagedGit implementation as a separate package? We developing our own versioning tool (due to our own versioning system) and currently depend on LibGit2Sharp. It would be nice if we were able to reuse your managed code.

Should I make a PR to add package build to this repo? Or should I maintain a fork for it?

Thanks!

**Comment by AArnott** [comment]
The possibility was discussed, but our means of funding the managed git implementation is limited and focused only to what nb.gv requires, so publishing a package for it out of this repo would seem to invite new users and scenarios that we are not prepared to support.

There were already other managed git nuget packages out there when we looked. Might any of those work for you? 
CC: @qmfrederik

**Comment by GlebChili** [comment]
@AArnott I see. Will look around for other managed implementations, maybe borrow your code. Thanks anyway!

**Comment by GlebChili** [comment]
If anyone finds this issue, I have created a requested library derived from `ManagedGit`: https://github.com/GlebChili/ManagedGitLib

I have extended the implementation with ability to work with all commit data, like committer and message, and added support for working with tags (both lightweight and annotated).

@AArnott I did my best to attribute the original work to you, Foundation, and other contributors. If something need to be done to make it more verbose, feel free to file an issue!

**Comment by AArnott** [comment]
Thanks for sharing. If you were listing names anywhere, @qmfrederik should get most of the credit as he wrote nearly all of it.

I think in some cases he deliberately left out reading some of the commit details for perf reasons. If your adding of these details can be done without regressing perf, we might at some point remove our own implementation in favor of switching to yours now that you have it separate.

Thanks for taking this on. Here's to the long and successful life of your repo. 🥂 (that's apple cider. I don't drink 😉)

**Comment by qmfrederik** [comment]
Thanks for letting us know, @GlebChili, and here's to a fully managed git read/write implementation!

You may want to give credits to @filipnavara too, as he played an important role in making this happen.

**Comment by GlebChili** [comment]
@qmfrederik @filipnavara I have mentioned you as original major contributors to `ManagedGit`: https://github.com/GlebChili/ManagedGitLib/commit/d4ad0d2fe8ce137dcb311551c5b7df8bda67d702. Feel free to open an issue in case you want to change something about the attribution.
