### ISSUE TITLE
Middleware hack for -- command line argument parsing can be removed

### ISSUE THREAD

**Issue by heaths** [dotnet/Nerdbank.GitVersioning#684]
https://github.com/dotnet/Nerdbank.GitVersioning/blob/9c1d6c6c9b7a72c383df01164a7fa1584d138011/src/nbgv/Program.cs#L205

Now that dotnet/command-line-api#1461 has been merged, it can be used instead of this temporary hack I put in place to handle post-`--` argument parsing, which the CLI supported previously.

**Comment by AArnott** [comment]
Has that merge made it to a public nuget.org package release though?

**Comment by heaths** [comment]
Not yet, no, but I wanted to open an issue while it was still fresh in my GitHub notifications.

**Comment by AArnott** [comment]
Fixed by 62389ed1feb4c01a33c4ca4ee928549ef3db1d35
