### ISSUE TITLE
Typo in ManagedGit ParentEnumerator.MoveNext causes incorrect behavior and ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by GlebChili** [dotnet/Nerdbank.GitVersioning#694]
Implementation of the `ParentEnumerator.MoveNext` method in `ManagedGit` contains a small typo, which leads to incorrect behavior and `System.ArgumentOutOfRangeException` while iterating when number of commit's parents is greater than 2:  
https://github.com/dotnet/Nerdbank.GitVersioning/blob/6f656c3f29904eaaec5e505b3f51ebdcb0e73d61/src/NerdBank.GitVersioning/ManagedGit/GitCommit.cs#L167

A non-strict inequality there should be replaced with a strict one.

I have opened a PR #693 which fixes the typo and adds a corresponding test. I'm testing against a real commit from [mono/mono](https://github.com/mono/mono) repository: https://github.com/mono/mono/commit/ab39e8acac105fa0db88514f259341c9f0201b22.
It is a quite old commit from the times when merge strategy allowed commits to have three parents.

**Comment by AArnott** [comment]
Great find. Incidentally, merges still allow more than two parents. I create them occasionally, but not enough apparently to hit this bug myself.
