### ISSUE TITLE
3.5 alphas incompatible with microbuild

### ISSUE THREAD

**Issue by sandyarmstrong** [dotnet/Nerdbank.GitVersioning#699]
I believe https://github.com/dotnet/Nerdbank.GitVersioning/pull/648 has regressed using this package with microbuild.

1. Bump NBGV version to `3.5.34-alpha` or later 
2. Run `dotnet build src/Editor/Core/Def/`

### Expected Results

Successful build.

### Actual Results

> /Users/sandy/.nuget/packages/nerdbank.gitversioning/3.5.34-alpha/build/Nerdbank.GitVersioning.targets(103,5): error : BuildMetadata items changed after a copy was made. Add all BuildMetadata items before importing this file. [/Users/sandy/xam-git/VS-Platform/src/Editor/Core/Def/CoreUtility.csproj]
/Users/sandy/.nuget/packages/nerdbank.gitversioning/3.5.34-alpha/build/Nerdbank.GitVersioning.targets(103,5): error : BuildMetadata items changed after a copy was made. Add all BuildMetadata items before importing this file. [/Users/sandy/xam-git/VS-Platform/src/Editor/Core/Def/CoreUtility.csproj]
    0 Warning(s)
    2 Error(s)

I commented-out the one place where this build touched `BuildMetadata`, then noticed that microbuild seems to be the culprit. 

I can work around the failure by setting `<MicroBuild_DoNotAppendBuildMetadata>true</MicroBuild_DoNotAppendBuildMetadata>` but I'm not sure if that's correct.

**Comment by AArnott** [comment]
Update to the latest Microbuild package and you should be good. (2.0.66)

**Comment by sandyarmstrong** [comment]
Ah, I thought `2.0.61` was the latest. I probably just need to add another upstream feed. Thanks!

**Comment by sandyarmstrong** [comment]
Weird, `2.0.61` is the latest in https://devdiv.visualstudio.com/DevDiv/_packaging?_a=package&feed=vs-impl&package=MicroBuild.VisualStudio&protocolType=NuGet&version=2.0.61&view=versions . I've been looking in other feeds and can't find where else it would be. Do you happen to know?

**Comment by AArnott** [comment]
You're looking at the discontinued package ID, as well as a feed that only shows versions that have already been consumed. Check out https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=vs-impl&package=Microsoft.VisualStudio.Internal.MicroBuild.VisualStudio&protocolType=NuGet&version=2.0.66

When you update your package ID and version, it should automatically show up in the feed you already were looking at.

**Comment by sandyarmstrong** [comment]
Thank you so much! Changing to the newer package IDs worked just as you said. I'll go ahead and close this. 😸
