### ISSUE TITLE
How do we specify a 3 segment Assembly Version (i.e. 0.4.1)?

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/Nerdbank.GitVersioning#703]
I am attempting to migrate an existing project to Nerdbank.GitVersioning. The thought put into how this works in CI environments is great, which is why we would like to use it on this project.

However, we are running into trouble because there doesn't appear to be a way to specify a 3-segment AssemblyVersion number, which is what the existing version specifies.

## Existing Version from NuGet

PackageVersion: 0.4.1
```c#
[assembly: AssemblyVersion("0.4.1.0")]
[assembly: AssemblyInformationalVersion("0.4.1.0 commit:[15dc7a18b9]")]
```

## Patch Version

Since this is a port of 0.4.1, we cannot change that part of the version number without causing user confusion (unless of course we also port over the changes from 0.4.2 or next higher version that exists). So, the patch should be versioned as follows.

PackageVersion: 0.4.1.1
```c#
[assembly: AssemblyVersion("0.4.1.0")] // Must remain the same for binary compatibility on .NET Framework
[assembly: AssemblyInformationalVersion("0.4.1.1 commit:[xxxxxxxxxx]")]
[assembly: AssemblyFileVersion("0.4.1.1")]
```

## What we tried

First I tried setting the `<GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>`, but that doesn't have any effect on the output of Nerdbank.GitVersioning.

I looked at the [schema of version.json](https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json) to see if there was an option to specify it explicitly and found `"assemblyVersion"` can be. But there is a problem: It defines the version as `major.minor`, so when I specify `"0.4.1"` it shows a warning and the AssemblyVersion is generated as `0.4.0.0` rather than the expected `0.4.1.0`.

Short of completely disabling Nerdbank.GitVersioning for our release build and using a custom script, is there any option to specify `0.4.1` as the AssemblyVersion?

**Comment by AArnott** [comment]
I'll have to check, but you may be right that our schema (and possibly internal parsing) for an explicit assembly version specified in `version.json` may not allow 3 integers. But you may find it simpler anyway to use the precision field instead:

```json
  "assemblyVersion": {
    "precision": "build"
  }
```

That will cause your standard `version` field to also apply to the assembly version, but instead of being truncated at the default of major.minor, it'll be truncated at major.minor.build. Would that suit you?

**Comment by NightOwl888** [comment]
For this release, I believe that could work.

For the remainder of the life of the project, maybe not. For all of our other projects we use:

```json
  "assemblyVersion": {
    "precision": "major"
  }
```

This is the correct behavior to make a strong named assembly break binary compatibility only when binary compatibility changes (at least if the project uses semantic vesioning).

But this project uses a weird versioning scheme. There were breaking changes between 0.3 and 0.4, but there doesn't seem to be any breaking changes between 0.4 and 0.8 (the current version). So, the path forward doesn't seem to be very clear in terms of compatibility. But what we will always do is bump AssemblyVersion *only* if binary compatibility is broken and we cannot produce a drop in replacement. We will need to handle that detail manually.

**Comment by AArnott** [comment]
Makes sense. I'll look into this later today.

Regarding your `precision: major` policy in general, that makes sense. I personally use `minor` as a default because adding new APIs is a *forward*-breaking change. That is, if someone compiles against 1.3.0.0 and then runs against 1.2.0.0, it'll fail if they use any of the new APIs added in 1.3.0.0. Investigating and fixing the bug is *much* faster with an exception about v1.3.0.0 not being found instead of a particular method not being found. 
So my own policy is all new APIs require a minor version bump, and that shows up in the assembly version. Yes, that means apps that use my libraries often need binding redirects, but those are usually auto-generated by msbuild nowadays anyway so it's rarely a problem.

**Comment by AArnott** [comment]
@NightOwl888 You can go ahead and use the assembly version with 3 components that you want in the version.json file. Per the PR I've filed, it already works -- the schema file just doesn't reflect that.

**Comment by NightOwl888** [comment]
I attempted both with 3.4.344 and 3.5.54-alpha, but got the same result each time.

```c#
[assembly: AssemblyFileVersion("0.4.1.1")]
[assembly: AssemblyInformationalVersion("0.4.1+5482e8d56c")]
[assembly: AssemblyVersion("0.4.0.0")]
```

The `version.json` file was committed as follows before the build:

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.4.1.1",
  "assemblyVersion": {
    "version": "0.4.1"
  },
  "versionHeightOffset": "0",
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/master$",
    "^refs/heads/release/v\\d+\\.\\d+(?:\\.\\d+)?(?:\\.\\d+)?$",
    "^refs/tags/v\\d+\\.\\d+"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

I made a second attempt with 3.4.253-gac36c2b649 (from Azure DevOps) setting the precision to "build" and it correctly output AssemblyVersion 0.4.1.

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.4.1.1",
  "assemblyVersion": {
    "version": "0.4.1",
    "precision": "build"
  },
  "versionHeightOffset": "0",
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/master$",
    "^refs/heads/release/v\\d+\\.\\d+(?:\\.\\d+)?(?:\\.\\d+)?$",
    "^refs/tags/v\\d+\\.\\d+"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

However, since it isn't possible to tell if that is due to the fact that it was simply ignoring `version` and using `precision`, I made an attempt to bump the version to the next real-world version of 0.5. It produces AssemblyVersion of 0.4.1, but the version number is 0.5.1.46059 instead of 0.5.

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.5",
  "assemblyVersion": {
    "version": "0.4.1",
    "precision": "build"
  },
  "versionHeightOffset": "0",
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/master$",
    "^refs/heads/release/v\\d+\\.\\d+(?:\\.\\d+)?(?:\\.\\d+)?$",
    "^refs/tags/v\\d+\\.\\d+"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

```c#
[assembly: AssemblyFileVersion("0.5.1.46059")]
[assembly: AssemblyInformationalVersion("0.5.1+ebb31694c8")]
[assembly: AssemblyVersion("0.4.1.0")]
```

I then attempted to use 0.5.0 as the version number instead of 0.5, and that made the assembly version revert to 0.4.0 (not to mention, it didn't set the version at 0.5.0 either, but the informational version is what I had hoped for).

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.5.0",
  "assemblyVersion": {
    "version": "0.4.1",
    "precision": "build"
  },
  "versionHeightOffset": "0",
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/master$",
    "^refs/heads/release/v\\d+\\.\\d+(?:\\.\\d+)?(?:\\.\\d+)?$",
    "^refs/tags/v\\d+\\.\\d+"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

```c#
[assembly: AssemblyFileVersion("0.5.0.1")]
[assembly: AssemblyInformationalVersion("0.5.0+3e982c4b05")]
[assembly: AssemblyVersion("0.4.0.0")]
```

Then I tried using `0.5.{height}` for the version number to see if I could use `versionHeightOffset` to wrangle `{height}` back to 0, but that generates an exception when trying to build:

```
F:\Users\shad\.nuget\packages\nerdbank.gitversioning\3.4.253-gac36c2b649\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.FormatException: Failure while reading version.json from commit df155680ba35f6008feea44574bcbdd542fe7bc6. Fix this commit with rebase if this is an error, or review this doc on how to migrate to Nerdbank.GitVersioning: https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/migrating.md ---> System.FormatException: The value "0.5.{height}" is not a valid semantic version.
```

Unfortunately, there are some strict rules in place that expect us to use semantic versioning. This is fine when you can use semantic versioning, but when porting code that needs to be version aligned and still needs to be patched in .NET to fix our mistakes, that doesn't seem to be possible.

While these are logical defaults, it would be great if this tool could:

1. Provide an option to turn off semantic versioning validation
2. Provide an option to pass in the 4 version arguments (package version, assembly version, file version, and informational version) to the nbgv tool as needed for the release, while calculating the omitted arguments as usual

All I am saying is that when using CI and dev it makes perfect sense to make the versions based on commit hashes rather than auto-incremented values that vary per environment. But when doing a release we need ultimate control over these values to prevent a versioning issue from blocking the release, such as aligning the versions to match some historical convention of the software we are releasing or to align the version to match an existing version we are porting.

**Comment by AArnott** [comment]
> Provide an option to pass in the 4 version arguments (package version, assembly version, file version, and informational version) to the nbgv tool as needed for the release

The `nbgv` tool doesn't influence your .NET build output. That would be the nerdbank.gitversioning package, which operates within msbuild and doesn't take arguments. Although it does respond to msbuild properties, which you can specify as global properties with the `/p:` switch at the command line. Each of these versions you mention *do* become msbuild properties before generating the .cs file that adds assembly attributes with the versions, so you already do have the opportunity to override them with the `/p:` switch.

> Provide an option to turn off semantic versioning validation

If this is based on the error you saw when setting `0.5.{height}`, the version spec you're going for is perfectly valid, but you need to drop the `.{height}` at the end. The `{height}` placeholder is only validly specified to the right of a `-`, and if you don't specify it anywhere, it's implied to be in the next version component you do not specify. Thus: `0.5` will have the behavior you're looking for as far as that goes.

Clearly the test I added didn't cover enough to guarantee your scenario works, so I will revisit this today or tomorrow to make sure you're unblocked, as what you're trying to do is absolutely reasonable and meant to be supported.

**Comment by NightOwl888** [comment]
> The nbgv tool doesn't influence your .NET build output.

By "tool", I meant the Nerdbank.GitVersioning project in general, not just the downloadable tool, which we do use.

> Although it does respond to msbuild properties, which you can specify as global properties with the /p: switch at the command line. Each of these versions you mention do become msbuild properties before generating the .cs file that adds assembly attributes with the versions, so you already do have the opportunity to override them with the /p: switch.

Okay, I must have something misconfigured, then. 

In `Directory.Build.props` we have AssemblyVersion defined near the top of the file.

```xml
  <PropertyGroup Label="Version Defaults">
    <!-- We are strong-named - never change this unless we increment major version. -->
    <AssemblyVersion>0.4.1</AssemblyVersion>
    <!-- Default for FileVersion, InformationalVersion, and PackageVersion if not passed in -->
    <Version>0.4.1.0</Version>
    <!-- IMPORTANT: Since this is a port, we are using the 4th (revision) number for patches.
         For example, if we don't port the changes of Spatial4j, the version after 0.4.1 should be 0.4.1.1, not 0.4.2! 
         If we do port the changes from Spatial4j, then we should increment the first 3 segments to be the same as the ported version. -->
  </PropertyGroup>
```
These were carried over from our old versioning scheme, but I haven't yet removed them.

Near the bottom of the same file, we are declaring the package reference:

```xml
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning">
      <Version>$(NerdBankGitVersioningPackageReferenceVersion)</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```


I tried changing the `version.json` file as follows, but it is completely ignoring the AssemblyVersion that I have configured in `Directory.Build.props`.

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.5.0",
  "assemblyVersion": {
    "precision": "revision"
  },
  "versionHeightOffset": "0",
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/master$",
    "^refs/heads/release/v\\d+\\.\\d+(?:\\.\\d+)?(?:\\.\\d+)?$",
    "^refs/tags/v\\d+\\.\\d+"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

```c#
[assembly: AssemblyFileVersion("0.5.0.2")]
[assembly: AssemblyInformationalVersion("0.5.0.2+3895149ab4")]
[assembly: AssemblyVersion("0.5.0.2")]
```

Then I tried completely removing the `assemblyVersion` element from `version.json` and it produced:

```c#
[assembly: AssemblyFileVersion("0.5.0.3")]
[assembly: AssemblyInformationalVersion("0.5.0.3+f3ad34a772")]
[assembly: AssemblyVersion("0.5.0.0")]
```

How should it be configured to allow the `AssemblyVersion` from MSBuild? Are the properties required to be set earlier or later in the pipeline?

**Comment by AArnott** [comment]
[These properties](https://github.com/dotnet/Nerdbank.GitVersioning/blob/8f06804010e9583ddd52e26eb6c976698044a9b3/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L122-L142) feed into the versioning that is stamped into your .NET assembly. Nerdbank.GitVersioning writes to these properties as part of the version calculation. If you want to override them, it can only be done as I specified, as *global* properties set with the `/p:` switch. Global properties cannot be overwritten in msbuild execution so although nb.gv will try to write to them, the new values will be discarded and your global properties will win.

But again, I hope to have a much better answer for you soon.

**Comment by AArnott** [comment]
When #707 completes, you'll be able to get the fix immediately by following [these instructions](https://github.com/dotnet/Nerdbank.GitVersioning#how-do-i-consume-the-latest-changes-prior-to-their-release-on-nugetorg). Getting your sign-off on the effectiveness of the fix will be great before a push a new prerelease to nuget.org.

**Comment by AArnott** [comment]
The version in the CI feed that includes this fix is 3.5.68-alpha.

**Comment by IanKemp** [comment]
Since all issues in the v3.5 milestone are completed, when can we expect to see that version released to NuGet?

**Comment by AArnott** [comment]
@IanKemp, 3.5's flagship feature is supposed to be support for msbuild `-graph` builds. I need to do some fresh testing of it to make sure it works. Then I think we can release.
