### ISSUE TITLE
"error : Version's parameters must be greater than or equal to zero." when setting versionHeightOffset negative

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/Nerdbank.GitVersioning#708]
Opening a separate issue, because it appears that #703 is now resolved, but there is another seemingly unrelated problem.

We _frequently_ set `versionHeightOffset` to a negative value to make the vNext the same as `current version + 1` upon release. But it is no longer functioning with a negative value (in 3.5.68-alpha).

```
F:\Users\shad\.nuget\packages\nerdbank.gitversioning\3.5.68-alpha\build\Nerdbank.GitVersioning.Inner.targets(17,5): error : Version's parameters must be greater than or equal to zero.
F:\Users\shad\.nuget\packages\nerdbank.gitversioning\3.5.68-alpha\build\Nerdbank.GitVersioning.Inner.targets(17,5): error : Parameter name: revision
```

The configuration used was

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.5.0",
  "assemblyVersion": {
    "version": "0.4.1"
  },
  "versionHeightOffset": "-7",
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/master$",
    "^refs/heads/release/v\\d+\\.\\d+(?:\\.\\d+)?(?:\\.\\d+)?$",
    "^refs/tags/v\\d+\\.\\d+"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

I confirmed that setting `versionHeightOffset` to a positive value eliminates the error message, so there is some validation that didn't exist in version 3.3.37 (the version we use in all of our other projects).

**Comment by NightOwl888** [comment]
Never mind. I reverted to 3.3.37 and discovered that my calculation was off, so the maximum amount I could decrement was 6 instead of 7.

**Comment by AArnott** [comment]
> We frequently set versionHeightOffset to a negative value to make the vNext the same as current version + 1 upon release. 

It sounds like you're fighting a battle unnecessarily then. I expect to meet this goal you make this adjustment just before release, which means your release version collides with a version built just after your last release. One of NB.GV design goals is to ensure you never build the same version twice from different source code. Also, it just seems like you don't want git height based versioning. Have you considered changing the settings in version.json to suppress version height contributing to version at all? That way you have ultimate control of the version and don't have to do hacks like this just before release.

**Comment by NightOwl888** [comment]
> Have you considered changing the settings in `version.json` to suppress version height contributing to version at all? That way you have ultimate control of the version and don't have to do hacks like this just before release.

I guess I haven't found that setting yet :). 

Actually, I was considering moving away from NB.GV before `versionHeightOffset` was introduced so we could eliminate gaps in versions between releases. But yea, it sounds like disabling version height would be easier to deal with than that, since CI builds already have a commit hash to make them unique, anyway.

While the issue around `assemblyVersion` seems settled now and having that in a configuration setting is ideal, I still need to experiment to see how to get the version we want. Worst case, since we already do [pass in all of the version parameters into the build](https://github.com/NightOwl888/J2N/blob/main/azure-pipelines.yml#L60-L63) in CI and we use a [common template to run nbgv](https://github.com/NightOwl888/J2N/blob/main/build/azure-templates/gitversioning-increment-and-persist-versions.yml) that is the same in all of our projects, we just need to modify it so it [doesn't overwrite any of the version variables](https://github.com/NightOwl888/J2N/blob/main/build/azure-templates/gitversioning-increment-and-persist-versions.yml#L54-L57) if they are already configured as variables in the build pipeline.

**Comment by NightOwl888** [comment]
> Have you considered changing the settings in `version.json` to suppress version height contributing to version at all? That way you have ultimate control of the version and don't have to do hacks like this just before release.

I just re-read this after looking for a setting to turn off version height and that isn't actually what you meant. But, I am curious what you did mean. 

### Expected Values

NuGet Package Version: 0.5.0
```c#
[assembly: AssemblyFileVersion("0.5.0.0")]
[assembly: AssemblyInformationalVersion("0.5.0+8878c6e815")]
[assembly: AssemblyVersion("0.4.1.0")]
```

### Actual Behavior

According to the [version.json schema](https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json):

```
"If {height} is not used in this value and the value has fewer than the full major.minor.build.revision specified, \".{height}\" will be appended by the build."
```

There doesn't seem to be a way to actually turn that behavior off, it always appends it to the end of the version unless I manually set it to `0.5.0.0`. 



But since I want the NuGet package version to be `0.5.0`, that doesn't cover me. If I set it to the actual version I want `0.5.0`, I get:

```
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.5.0",
  "assemblyVersion": {
    "version": "0.4.1"
  },
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/master$",
    "^refs/heads/release/v\\d+\\.\\d+(?:\\.\\d+)?(?:\\.\\d+)?$",
    "^refs/tags/v\\d+\\.\\d+"
  ],
  "cloudBuild": {
    "buildNumber": {
      "enabled": true
    }
  },
  "release": {
    "branchName": "release/v{version}"
  }
}
```

```c#
[assembly: AssemblyFileVersion("0.5.0.4")]
[assembly: AssemblyInformationalVersion("0.5.0.4+c37c8247ef")]
[assembly: AssemblyVersion("0.4.1.0")]
```

The only way to correct this is to set the `versionHeightOffset` to -4 to zero it out. However, `AssemblyInformationalVersion` still has the extra 0 I don't really want.

```c#
[assembly: AssemblyFileVersion("0.5.0.0")]
[assembly: AssemblyInformationalVersion("0.5.0.0+ea31be2201")]
[assembly: AssemblyVersion("0.4.1.0")]
```

By using `"version": "0.5"`, `AssemblyInformationalVersion` can be fixed. However, that changes `AssemblyFileVersion` to append a 5 digit revision (not even sure where that value is coming from). I didn't check the NuGet package in this case, but I suspect it would either choose 0.5.0.34936 or 0.5, since there is nothing in the configuration setting it to 0.5.0.

```c#
[assembly: AssemblyFileVersion("0.5.0.34936")]
[assembly: AssemblyInformationalVersion("0.5.0+8878c6e815")]
[assembly: AssemblyVersion("0.4.1.0")]
```

If there is a configuration that can be used to get these values, please do tell. If not, maybe there should be a boolean setting to turn off the automatic `.{height}`...? That would certainly cover this scenario.

**Comment by AArnott** [comment]
> it always appends it to the end of the version unless I manually set it to 0.5.0.0.

Yes, exactly. That's how you turn it off the addition of version height. 

> But since I want the NuGet package version to be 0.5.0, that doesn't cover me

This should _not_ force nuget package versions to be 0.5.0.0 because [nuget package versions are always forced to 3 components](https://github.com/dotnet/Nerdbank.GitVersioning/blob/0e7febc2b1cee560376eb53ea962f4eb47ed69ff/src/NerdBank.GitVersioning/VersionOracle.cs#L417-L418). So 0.5.0.0 would produce a nuget package version of 0.5.0.

It seems that if you want to control all these versions completely, I can't think of any value nerdbank.gitversioning is providing to you other than generation of the assemblyinfo.cs file. Just about everyone wants a unique version produced per-commit if they're using a git-based versioning system. In same cases like AssemblyVersion the version has a real impact on functionality so we allow some constraining of that. And some folks are particular about wanting their nuget package versions to only increment by one patch version for each release, and this can be controlled by setting 3 components of their `version` property as well. But for the insignificant version fields like `AssemblyFileVersion` and `AssemblyInformationalVersion` folks tend to appreciate how precise that can be for pointing folks to the exact git commit that produced it. If you don't want that (and it sounds like you don't), I wonder if there's any value left for you that NB.GV offers.

**Comment by NightOwl888** [comment]
> But for the insignificant version fields like AssemblyFileVersion and AssemblyInformationalVersion folks tend to appreciate how precise that can be for pointing folks to the exact git commit that produced it. If you don't want that (and it sounds like you don't), I wonder if there's any value left for you that NB.GV offers.

Actually, this is fine, I was just asking whether it is possible to utilize NB.GV without breaking the existing convention. But if not, I don't think it is a problem.

> I can't think of any value nerdbank.gitversioning is providing to you other than generation of the assemblyinfo.cs file. Just about everyone wants a unique version produced per-commit if they're using a git-based versioning system.

So do we, for CI purposes. For the release, we need tighter control because we have a special case.

For [Lucene.NET](https://github.com/apache/lucenenet), we are currently using the auto incrementing settings of Azure DevOps to generate the version numbers. There are some problems with this approach that could be solved by migrating to NB.GV:

1. The auto-incremented number is different on each one of our CI environments (we use several to get around the 10 concurrent job limitation), and we sometimes have version collisions.
2. The auto-incremented number resets when the builds are cleaned up if not run for X days.
3. The same commit produces multiple version numbers.
4. While not directly related to versioning, we currently are only set up to release on the master branch, which means we sometimes update documentation days ahead of when it becomes valid, since we have a [72 hour mandatory delay for each release](https://lucenenet.apache.org/contributing/make-release.html).

Of course, all of these issues could be addressed by switching to NB.GV instead of our custom powershell script (which only exists because we were an early adapter of .NET Core when Microsoft still hadn't decided between JSON or XML for the new build chain). This of course adds value (and so would anything else that knocks manual tasks off of our release procedure).

It would be great if NB.GV could handle the [special versioning rules](https://lucenenet.apache.org/contributing/versioning.html) for switching between pre-release and 4 segment release, since NuGet doesn't support a 4-segment pre-release version. We need to be able to use a 3-segment build number for CI, and then add the 4th segment upon release, so we can align the first 3 segments to the ported version we are patching. This isn't set in stone if another reasonable idea comes along, but so far, we haven't come up with a good one.

Since we have already established that any values that the nbgv tool produces can be replaced before executing the dotnet build command, I think we are also covered for the release in that regard, we just have to put the versioning rules to the right place in the pipeline and/or release procedure to make it work.

**Comment by AArnott** [comment]
> since NuGet doesn't support a 4-segment pre-release version

Can you give me an example of a package version nuget doesn't support? Do you mean nuget as a packaging system (i.e. the tools) or nuget.org specifically? From the doc you linked to it sounds like `1.2.3.4-pre` isn't supported (by nuget.org?). Is that correct? 

Based on the version rules you linked to, which I get how you want to be based on Lucene's own version number, I don't have a concrete set of steps or settings you can use to play nicely with everything. You may be doing the best you can already.

**Comment by NightOwl888** [comment]
> Can you give me an example of a package version nuget doesn't support? Do you mean nuget as a packaging system (i.e. the tools) or nuget.org specifically? From the doc you linked to it sounds like 1.2.3.4-pre isn't supported (by nuget.org?). Is that correct?

It took me awhile to find it, but I am referring to [this article](https://www.xavierdecoster.com/post/2013/04/29/semantic-versioning-auto-incremented-nuget-package-versions.html) by Xavier Decoster, co-founder of MyGet.org. It is a bit dated now: it was written before NuGet supported SemVer 2.0.

He recommends not to use a 4th version number because it isn't semver compliant, but I am not seeing another logical choice that makes sense.

Hmm, looks like I mis-remembered this. According to the article, NuGet has historically supported `major.minor.build.revision[-prerelease]`. I was able to build and pack both 0.5.0.6-beta and 0.5.0.6-beta-20. 

But it will take quite a bit more experimenting to find out whether:

1. NuGet.org will allow these versions to be uploaded
2. The NuGet version resolution tools can tell which version is the *latest*, and which versions of those tools provide this support, since pre-release label historically were sorted lexographically

**Comment by AArnott** [comment]
I think nuget.org recognizes a semver 2 vs 1 versioned package and applies sorting rules accordingly.

**Comment by NightOwl888** [comment]
## NuGet.Versioning

FYI - I found a simple way to test the version sorting rules:

https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#where-nugetversion-diverges-from-semantic-versioning

The package [NuGet.Versioning](https://www.nuget.org/packages/NuGet.Versioning) has a comparer and a `NuGetVersion.Parse()` method that validates the string, so I was able to quickly verify that the expectations about a 4 segment version number.

![image](https://user-images.githubusercontent.com/1538288/147841821-99960756-dede-4171-b459-5318621e6d3f.png)


## 4 Segments

I ran into a bit of a snag because of the bit that forces to a 3 segment version number for:

- NBGV_NUGETPACKAGEVERSION
- NBGV_ASSEMBLYINFORMATIONALVERSION

Any chance you can add a non-default feature `allowLegacyNuGetVersions` to allow 4 segment version numbers when I submit them via global properties? I realize other package managers don't support this, but we won't be using anything but NuGet.

Instead of switching from 3 segments for prerelease into 4 segments for release, we'd like to go with 4 segments in both cases, since NuGet supports it (which simplifies things a lot). Of course, our initial release for each port will have 3 segments, the 4th segment will only be used for .NET patches that don't exist in Java.

## Workaround Weirdness

For now, I have set it up so in CI it just uses the nbgv tool to generate the numbers and then I parse/concat them until I get the versions I need, and it removes the package reference to NB.GV so it doesn't chop off the version at 3 segments. However, for some reason, it is appending the full commit hash to the end of InformationalVersion even though the value passed into the dotnet build command doesn't include it. I ended up removing the partial commit hash for the time being.

```
[assembly: AssemblyFileVersion("0.4.1.1")]
[assembly: AssemblyInformationalVersion("0.4.1.1-alpha.1+331f5970dd2f407cc94d6bcb090fe1b785546b4c")]
[assembly: AssemblyVersion("0.4.1.0")]
```

**Comment by AArnott** [comment]
FYI You can override any nbgv version property in msbuild you want using a custom msbuild target:

```xml
<Target Name="Set4ComponentNugetVersion" AfterTargets="GetBuildVersion">
  <PropertyGroup>
    <NuGetPackageVersion>$(YourCustomVersion)</NuGetPackageVersion>
  </PropertyGroup>
</Target>
```

The `GetBuildVersion` target unconditionally sets many properties, but by scheduling your target to run right after, you can re-set them to whatever you want. Then, when the msbuild target runs that sets the c# attributes for your assembly, it'll use the values you defined.

I don't object to a new setting to allow 4-component nuget versions to be computed automatically though. If it did, would it just pull all 4 components from the same version used for AssemblyFileVersion? Would that work for you?

**Comment by NightOwl888** [comment]
Thanks for the tip.

> I don't object to a new setting to allow 4-component nuget versions to be computed automatically though. If it did, would it just pull all 4 components from the same version used for AssemblyFileVersion? Would that work for you?

Yes, that is exactly what I had in mind - use 4-component "Version" to set both the FileVersion and AssemblyFileVersion.

There is one additional thing that prevents us from using NB.GV in Lucene.NET, though. Our beta versions are padding to 5 digits (which is supported), but we also don't separate the label and counter with a "-". 

https://www.nuget.org/packages/Lucene.Net/4.8.0-beta00015

It isn't that big of a deal for us to fix, but it would be better if there were some way to exclude the delimiter between those values, if possible.

**Comment by AArnott** [comment]
I expect you've already considered (and dismissed) the switch to semver 2?
I may be able to look into removing the required separator you mention. 

Can you open two new issues, one tracking the separator and one tracking the 4-component nuget version?

**Comment by NightOwl888** [comment]
Yea, I have tried semver 2, but that really doesn't solve the issue with patching a ported component that is version-aligned with the Java version.
