### ISSUE TITLE
Missing release v3.4.255

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/Nerdbank.GitVersioning#713]
[Nerdbank.GitVersioning/3.4.255](https://www.nuget.org/packages/Nerdbank.GitVersioning/3.4.255) was published to the NuGet Gallery <span title="2022-01-06T20:32:06Z">11 hours ago</span>. The release notes in the NuGet package say _"See https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.4.255 for release notes"_ but there is no such release in this repository yet.

The NuGet metadata refers to commit 06fb9182bf043a37137cf852ecf2e179127bb177, which is in this repository. [Comparison to v3.4.244](https://github.com/dotnet/Nerdbank.GitVersioning/compare/v3.4.244...06fb9182bf043a37137cf852ecf2e179127bb177).

(Noticed from @dependabot PR <https://github.com/dotnet/docfx/pull/7811>.)

**Comment by AArnott** [comment]
Oops. Fixed: https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.4.255
