### ISSUE TITLE
Project versioning does not adhere to it's own version.json

### ISSUE THREAD

**Issue by takato1314** [dotnet/Nerdbank.GitVersioning#730]
## Introduction
I am currently working on a monorepo with several projects that requires different versioning. I came across the documentation about [Path Filters](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/pathFilters.md#problem) and #612 to understand on what needs to be done. I have a [sample monorepo solution](https://github.com/takato1314/Nerdbank.GitVersioning.BugDemo) created to illustrated the problem below.

## Problem
Basically the [monorepo](https://github.com/takato1314/Nerdbank.GitVersioning.BugDemo) has the similar structure as the [problem mentioned in Path Filter doc](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/pathFilters.md#problem).

- {root}
  - /src
    - /p1
      - [version.json](https://github.com/takato1314/Nerdbank.GitVersioning.BugDemo/blob/main/src/p1/version.json)
    - /p2
    - /p3
      - [version.json](https://github.com/takato1314/Nerdbank.GitVersioning.BugDemo/blob/main/src/p3/version.json)
  - /test
  - [version.json](https://github.com/takato1314/Nerdbank.GitVersioning.BugDemo/blob/main/version.json)

Note that only p1 and p3 has their own version.json, while p2 doesn't has any. The idea and expectation here is that the default versioning for those nested projects without their own version.json should follow the default version, i.e. 1.0-beta, while those with their own version.json should follow the version specified there.

However, the outcome is not as described earlier, and all projects p1-p3 always follow the default version, i.e. 1.0-beta, as shown below:
![image](https://user-images.githubusercontent.com/10910968/159064630-1a00b031-4256-4157-aa02-56f4a0b8bfe1.png)

The version generated from the command `nbgv get-version` however seems to be correct and matches with what I wanted.
![image](https://user-images.githubusercontent.com/10910968/159064040-f47aac6a-6739-4f4c-9aa0-425b43e55c92.png)

Could you perhaps look at the sample [monorepo project](https://github.com/takato1314/Nerdbank.GitVersioning.BugDemo) and enlighten me if there's something that i missed or if it's a bug?

**Comment by KalleOlaviNiemitalo** [comment]
You have a `src/p1/version.json` file, but that project inherits `<GitVersionBaseDirectory>$(MSBuildThisFileDirectory)</GitVersionBaseDirectory>` from the root `Directory.Build.props`, so the `GitVersionBaseDirectory` property does not point to the directory that contains the most specific `version.json` file.

**Comment by takato1314** [comment]
My bad, that's really silly of me to miss that out. It is mentioned in this [documentation](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/msbuild.md#reducing-getbuildversion-invocations) as well.
