### ISSUE TITLE
Is there a way to completely override the version on the command-line?

### ISSUE THREAD

**Issue by IanKemp** [dotnet/Nerdbank.GitVersioning#731]
I need a completely ad-hoc versioned package to test against locally, so I'm running:

`
PS> dotnet pack --nologo --include-symbols --output C:\DevNuGet -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:PublicRelease=False -p:PrereleaseVersion=2.0.3-dev001
`

but the final version that's stamped is still the NBGV pre-release version. I've also tried specifying the standard MSBuild `Version` property with and without setting `PublicRelease`, with the same result.

I've tried using various of the variables defined [here](https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/msbuild.md#msbuild-properties-defined-in-getbuildversion) on the command-line, but none of them appear to be overridden.

It could possibly be argued that I'm asking to disable NBGV completely, which would be covered by #568, but I was under the impression that properties set on the command-line override those set by tasks.

**Comment by AArnott** [comment]
Which version do you really need to override? The nuget package version? The assembly version? the file version? Each version has its own msbuild property, which you could probably override at the CLI as you're trying to do, but with the wrong property names.

**Comment by IanKemp** [comment]
All I want to do is set the NuGet package version to a specific one I provide. The problem is that overriding the NBGV properties on the CLI **doesn't do anything**, regardless of which properties I use. This happens regardless if I set `PublicRelease` to true or false.

**Comment by AArnott** [comment]
> regardless of which properties I use

Which properties are you trying? Have you tried `/p:NugetPackageVersion=1.2.3`?

**Comment by IanKemp** [comment]
> > regardless of which properties I use
> 
> Which properties are you trying? Have you tried `/p:NugetPackageVersion=1.2.3`?

Yup:

```ps
PS> dotnet pack ".\Project.csproj" --nologo --no-build  --include-source /p:SymbolPackageFormat=snupkg /p:PublicRelease=false /p:"NuGetPackageVersion=4.2.23-dev1"
```

But the end result is that the package ends up versioned as 4.2.22-g745fae4457.

**Comment by AArnott** [comment]
I'll have to try it locally and figure out why that didn't work.

**Comment by AArnott** [comment]
I just tested it, and I guess there isn't a way to override it at the command line. You have to inject an msbuild target after `GetBuildVersion` in order to set properties after it runs. 

So for example, you could add this to your project file (or something it imports):

```xml
<Target Name="HackVersion" AfterTargets="GetBuildVersion" Condition="'$(OverridePackageVersion)'!=''">
  <PropertyGroup>
    <PackageVersion>$(OverridePackageVersion)</PackageVersion>
  </PropertyGroup>
</Target>
```

Then the `dotnet pack -p:overridepackageversion=1.2.3` command will actually build the package with the version you specify at the CLI.

Just know that by doing this, you're leaving a lot of functionality that NB.GV behind. For example the `nbgv` CLI tool won't be able to work backwards to tie a package version number to the commit that produced it.

**Comment by IanKemp** [comment]
@AArnott The scenario I require this for is:

* Package A version 1.0.1 (versioned via NBGV)
* Application B consumes A.1.0.1
* Bug reported in B that turns out to be caused by A and can be resolved by fixing A then upgrading it in B (i.e. no code changes in B)

Thus my workflow is:

* Fix the bug in A on my local machine
* Build and package my fixed A as an arbitrary prerelease version **that is newer than the released version of A**. Generally I use major.minor.(release + 1)-dev-(revision), so for A I'd make it 1.0.2-dev001. Then copy A.1.0.2-dev001 to a local, temporary NuGet repo on my machine:
`dotnet pack --nologo --include-symbols --output C:\DevNuGet -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:Version=1.0.2-dev001`
* Open the B solution in Visual Studio and add the aforementioned repo as a package source
* In the B solution, open the "Manage NuGet packages" dialog, navigate to the "Updates" tag, tick "Include prerelease", select A.1.0.2-dev001
* Test B to ensure that the bug is fixed
* If not, iterate with A.1.0.2-dev002, A.1.0.2-dev003, etc.
* Once bug is confirmed fixed, push my changes to A as a new branch that gets built with NBGV into an official A.1.0.2 package and pushed to our internal NuGet feed
* Finally, update B to use A.1.0.2 and push that change as a new branch

Note that in this workflow, **I neither want nor need NBGV to do anything for me** - I am controlling the version numbers explicitly.

Granted, if I first made a new branch for A and every one of my changes (including abortive ones) were pushed as discrete commits on that branch, then NBGV would of course work as expected. And since we use squash merges, the abortive attempts wouldn't ever make it into the commit history. But.. that's not my workflow, for better or worse.

**Comment by AArnott** [comment]
> Granted, if I first made a new branch for A and every one of my changes (including abortive ones) were pushed as discrete commits on that branch

No need to _push_ those commits. Just commit them locally. You can even amend the same commit repeatedly and you'll still get unique package versions every time, but the 'incremental' nature of the version would be gone and all you'd have left are the unique commit id's in the package version unstable tag.
Other than that, yes this other approach you mention is the one I use regularly. It seems to me that manually choosing a package version every time you iterate here is just more work.
