### ISSUE TITLE
nbgv get-version against commit IDs gives output like 0.0.0-g76419bb435, is this correct?

### ISSUE THREAD

**Issue by bengeset96** [dotnet/Nerdbank.GitVersioning#736]
Hi, 

Just trying to implement this awzm tool in CI/CD. 

This is the script.

![image](https://user-images.githubusercontent.com/99641908/165185792-de79fce5-b4fa-4aec-834a-345db6a665a5.png)

![image](https://user-images.githubusercontent.com/99641908/165185860-e65a83eb-1f33-4687-9f96-ec02cd03c1a1.png)

I was expecting 1.0.1 for base (HEAD~) and head (HEAD) to be 1.0.2

I have even tried to hardcode the version.json file with something like 1.2 and still it is giving me 0.0.0-gXXXXXXXX

What kind of rookie mistake am I doing? 

I can add I am doing checking out the repo before starting the Pwsh task and have many version.json files in the repo like this. 

![image](https://user-images.githubusercontent.com/99641908/165186383-e4a3ba8d-ec59-4c2d-a8a0-9c0db455f6cc.png)

**Comment by AArnott** [comment]
Where are your version.json files? If you don't have one in the root of your repo, that would explain it. You would need to specify the `--project` parameter to `nbgv get-version` to help it find the right version.json to calculate the version from.

**Comment by bengeset96** [comment]
@AArnott 

Issue has been identified and fixed. User fault as everything else..

Two things. I did not use PublicRelease property and was not running get-version in the directory where I want to compare. 

This is now taken care of and it works fantastic. Gamechanger!
