### ISSUE TITLE
BuiltProjectOutputGroupDependencies target missing after updating Nerdbank.GitVersioning to 3.5.x

### ISSUE THREAD

**Issue by josesimoes** [dotnet/Nerdbank.GitVersioning#751]
Hey!

After upgrading to the latest 3.5.103 a VSIX project I have it's failing with the error:

`C:\Users\VssAdministrator\.nuget\packages\nerdbank.gitversioning\3.5.103\build\PrivateP2PCaching.proj : error MSB4057: The target "BuiltProjectOutputGroupDependencies" does not exist in the project.`

Reverting to 3.4.255 "fixes" it. Any hints on where I should look?

**Comment by AArnott** [comment]
There is no vsix. I presume you mean nuget package.

Yes, this is a risk of the 3.5 upgrade on account of it being made to work with msbuild's static graph feature. You can see a little history over at #688.

**Comment by josesimoes** [comment]
Excuse my bad English... I was trying to explain that this happened to me when updating a VSIX project on which I'm using nbgv.
Everything works fine with 3.5.103 in other class library projects where it's being used.

I'll take a look at #688 as you're suggesting and see if I can find something.

**Comment by AArnott** [comment]
I'd love to see if #752 resolves your issue. Are you comfortable with nuget enough to download the nupkg from the PR build and give it a try?

**Comment by josesimoes** [comment]
> I'd love to see if #752 resolves your issue. Are you comfortable with nuget enough to download the nupkg from the PR build and give it a try?

Yeap! I can give it a try.

**Comment by josesimoes** [comment]
@AArnott I've started by implementing your suggestion above. It fixed it but a new error popped complaining about another target missing `DebugSymbolsProjectOutputGroup`. 
I've added that one too to the "dummy" targets. 😅  The build when fine afterwards.

You may want to take a look at the PR when these nanoframework/nf-Visual-Studio-extension#719.

**Comment by AArnott** [comment]
Great. It was additional missing targets that I was mostly curious about. I've updated my PR. Your existing validation covers what I was looking for, so I'll complete the PR when its build is done. Thank you.
