### ISSUE TITLE
Version schema file not found

### ISSUE THREAD

**Issue by EluciusFTW** [dotnet/Nerdbank.GitVersioning#762]
I'm unsure if this is an issue here, so please feel free to close this.

The [schema file](https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json)
does not seem to exist anymore:

![image](https://user-images.githubusercontent.com/10219667/168250540-5d473dee-030f-4c38-99fc-5817750b0ecf.png)

**Comment by EluciusFTW** [comment]
I changed _master_ in the path to _main_, and now it is found again. Did it move recently, as I'm sure it worked with master a few months ago?

**Comment by KalleOlaviNiemitalo** [comment]
According to <https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch>, "raw file URLs are not redirected." This information was added to the docs in <https://github.com/github/docs/pull/4830/> in April 2021 so it's not a recent change.

Maybe the `master` branch was not deleted immediately when  `main` was added? The `version.json` file in this repo referenced the `master` branch until <https://github.com/dotnet/Nerdbank.GitVersioning/commit/3c38b4d178ff5ef5a6a7ace778560ec3f8b4cb43#diff-093664cc0c7cf4a76165141e93265eeb139f655bbee8105ed3ee2534a612354c>.

**Comment by AArnott** [comment]
I don't know about that doc, but the raw URL _is_ being redirected. `master` was renamed to `main` just yesterday. The raw URL you've been using _would_ still work, except that I also changed the capitalization of the path, which _doesn't_ get forwarded.


Original url: 
https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/Nerdbank.GitVersioning/version.schema.json
