### ISSUE TITLE
Again: GetTargetPathWithTargetPlatformMoniker target missing but on 3.5.104

### ISSUE THREAD

**Issue by LevYas** [dotnet/Nerdbank.GitVersioning#764]
Hi! Funny thing, I see you added the target in response to https://github.com/dotnet/Nerdbank.GitVersioning/issues/754, but I also see the error on my CI machine:

```
"D:\a\***\Source\My.sln" (default target) (1) ->
"D:\a\***\Source\Installer\Installer.wapproj" (default target) (22) ->
"C:\Users\runneradmin\.nuget\packages\nerdbank.gitversioning\3.5.104\build\PrivateP2PCaching.proj" (GetTargetPathWithTargetPlatformMoniker target) (13:68) ->
  C:\Users\runneradmin\.nuget\packages\nerdbank.gitversioning\3.5.104\build\PrivateP2PCaching.proj : error MSB4057: The target "GetTargetPathWithTargetPlatformMoniker" does not exist in the project.
```

The only difference I see is that I have WAPPROJ file (Windows Application Packaging Project, in my case it's MSIX Installer project), and the person in the mentioned issue had CSPROJ.
The project built successfully many times, the latest successful build used nerdbank.gitversioning 3.4.255.

Thank you.

**Comment by AArnott** [comment]
Ah, that PR isn't in 3.5.104. It's in 3.5.107, which hasn't pushed to nuget.org. 
I'm pushing now though.
