### ISSUE TITLE
The target "VSTest" does not exist in the project

### ISSUE THREAD

**Issue by craigktreasure** [dotnet/Nerdbank.GitVersioning#774]
Getting an error after upgrading to 3.5.107 and running `dotnet test`:
```
.nuget\packages\nerdbank.gitversioning\3.5.107\build\PrivateP2PCaching.proj : error MSB4057: The target "VSTest" does not exist in the project.
```

Any suggestions?

Last working version is 3.4.255.

**Comment by AArnott** [comment]
Thanks for reporting. Check out [our release notes](https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.5.103) for a workaround while waiting for another update to address this.

**Comment by alexrp** [comment]
@AArnott The workaround described there doesn't seem to work with 3.5.108 - I still get `error MSB4057: The target "VSTest" does not exist in the project.` with an empty `VSTest` target defined in a file imported by setting `NBGV_PrivateP2PAuxTargets`... 🤔

Any chance a39b14e9cd5b2cbaf88fa5e3ae8468392d846308 is going to be included in a release soon?

**Comment by AArnott** [comment]
That commit was unfortunately made on `main` instead of v3.5. bdfbd7d is the cherry-picked commit for v3.5.
