### ISSUE TITLE
Support for signing tags with `dotnet nbgv tag`

### ISSUE THREAD

**Issue by alexrp** [dotnet/Nerdbank.GitVersioning#785]
It would be nice if `dotnet nbgv tag` could get an option to sign commits. Currently, I have to do something like:

```
dotnet nbgv tag
# Update tag as signed and with message set to its name (signed tags require a message).
git tag v0.1.2 v0.1.2 -f -m v0.1.2 -s
```

Being able to instead do `dotnet nbgv tag -s` would be much nicer. Bonus points for an `-m` option, though I'm perfectly happy with just using the tag name as the message.

**Comment by AArnott** [comment]
Ya, we'll close as a duplicate of #594
