### ISSUE TITLE
Publish v3.5.108 in GitHub releases

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/Nerdbank.GitVersioning#786]
There is [Nerdbank.GitVersioning 3.5.108](https://www.nuget.org/packages/Nerdbank.GitVersioning/3.5.108) in NuGet Gallery now. Could you please publish `v3.5.108` in [GitHub releases](https://github.com/dotnet/Nerdbank.GitVersioning/releases) as well? Especially because the release notes in the NuGet package now have a broken link:

> See https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.5.108 for release notes.
> IMPORTANT: The 3.x release may produce a different version height than prior major versions.

**Comment by AArnott** [comment]
Done.
