### ISSUE TITLE
Warning about PrivateP2PCaching.proj

### ISSUE THREAD

**Issue by gnampf89** [dotnet/Nerdbank.GitVersioning#787]
When building in Visual Studio 2022 for each project in the solution I receive this warning:
`The referenced component 'C:\Users\XXX\.nuget\packages\nerdbank.gitversioning\3.5.108\build\PrivateP2PCaching.proj' could not be found.`

The file exists. At least after the build. Otherwise everything seems to be working as it should (version from config file gets correctly applied to each project/assembly)

I set up GitVersioning using `nbgv install` on the solution level folder.

**Comment by gnampf89** [comment]
latest VS 2022 (17.2.6)
WinForms Libraries and Applications targeting .net Framework 4.7.2 (show Warning)
ASP.Net web-app targeting Framework 4.8 (shows warning)
.net libs targeting .net standard 2.0 (no warning)
.net apps targeting .net 6.0 (no warning)
so essentially the projects that use the old project format (where every file needs to be in the file) have the problem.

**Comment by gnampf89** [comment]
Found something: created a new solution .net 60 console project and 4.8 Framework Console project and the warning appeared on when I added the generated Directory.Build.props to the `Solution Items` (I like to add top level items for easy access within Visual studio).

So when I removed it and deleted the broken reference in all projects, the warning went away, both in the test solution and in my real solution.

I was not aware, that "Solution Items" had more function than a simple container. The `version.json` is still there without problem

**Comment by AArnott** [comment]
Thank you, @gnampf89, but I'm still unable to repro with a new WinForms App project where I've installed NB.GV. Can you provide a repro solution?

**Comment by gnampf89** [comment]
Sorry for the delay.
I created a [demo](https://github.com/gnampf89/nbgvtest) solution. 
no Warning on the first compile. If I close VS2022, reopen, compile again (F6) the warning appears.

**Comment by AArnott** [comment]
Ok, I see it now. Thank you. I filed a feedback ticket against VS to address this. Hopefully they will fix it in VS because there's nothing NB.GV can do here short of abandoning its private ProjectReference design, which MSBuild requires until https://github.com/dotnet/msbuild/issues/6852 is addressed.
