### ISSUE TITLE
[Proposal] Introduce shared public interface for 'ThisAssembly' implementation

### ISSUE THREAD

**Issue by julealgon** [dotnet/Nerdbank.GitVersioning#788]
I'd like to be able to tap into the `ThisAssembly` information from an external extensions project. For that to work, I think the simplest approach would be to introduce an interface that sits in a dll as part of this package, or a `Nerdbank.GitVersioning.Core`-like dependent package, and then generate the `ThisAssembly` class by implementing that interface. Then, an extensions project could reference the library and take the interface as an argument. Since `ThisAssembly` is currently static, this would probably require a change to at least make it a singleton with a non-static `Instance` property, or it could rely on .NET7's static abstract interfaces.

For context, the extension I'm trying to create is related to OpenTelemetry. OTel requires you to set the "service" that will be emitting logs/metrics/traces, otherwise it defaults to `unknown_service_{process_exe_name}`. What I wanted to create was a Nerdbank.GitVersioning-based `IResourceDetector` implementation that automatically populates OTel's `service.name` and `service.version` metadata.

For that to be possible, I need to access fields like `AssemblyInformationalVersion` and maybe `AssemblyTitle` to use as the sources, either through dependency injection, or through direct parameter. For me to be able to do either of those, I need to have some public reference to the schema on the class, either making it public itself, or making a public interface for it. The interface approach seems more adequate to me as it doesn't overexpose the concrete implementation in the target project.

My current workaround will probably rely on creating this interface myself (in my own extension project), then asking consumers to implement it in their projects through the `partial` extensibility in `ThisAssembly` either via a wrapper, or a singleton implementation. This is obviously less than ideal as it will incur extra dev work on every consumer of the extension for it to work cleanly.

**Comment by AArnott** [comment]
How would your extension acquire an instance of this interface? Via reflection? 
Why would you want to limit yourself to just those assemblies that happen to use NB.GV when all (or nearly all) of the information in `ThisAssembly` is already in assembly-level attributes like `AssemblyTitleAttribute` and `AssemblyInformationalVersionAttribute`? You can use reflection on _any_ assembly to get those attributes and inspect their values, assuming the assembly applies those attributes, which all NB.GV-built assemblies do, and so many more.

**Comment by julealgon** [comment]
@AArnott 

> How would your extension acquire an instance of this interface? Via reflection? 

That would be an option, or I could just ask for it as an argument either directly in the OTel extension, or as an extension on the container that registers it in dependency injection and allows me to fetch it later in the implementation.

> Why would you want to limit yourself to just those assemblies that happen to use NB.GV when all (or nearly all) of the information in `ThisAssembly` is already in assembly-level attributes like `AssemblyTitleAttribute` and `AssemblyInformationalVersionAttribute`? You can use reflection on _any_ assembly to get those attributes and inspect their values, assuming the assembly applies those attributes, which all NB.GV-built assemblies do, and so many more.

I could ask you back here and question why does `ThisAssembly` exist in the first place if we can already gather the information from the attributes as well? 

I just wanted to have a single source of truth for this info when using this versioning library. No stronger reason than that to be honest. Reading the same info from different places feels like a code smell to me: if places are using `ThisAssembly`, then we should use it consistently everywhere.

But yeah, reading from the attributes directly and completely "ignoring" nbgt is an option for sure.

**Comment by julealgon** [comment]
> Can't you use [CustomAttributeExtensions.GetCustomAttribute<T>(this System.Reflection.Assembly element)](https://docs.microsoft.com/dotnet/api/system.reflection.customattributeextensions.getcustomattribute?view=net-6.0#system-reflection-customattributeextensions-getcustomattribute-1(system-reflection-assembly)) with T being AssemblyInformationalVersionAttribute and AssemblyTitleAttribute?

I definitely can @KalleOlaviNiemitalo , but I'd rather rely on a single abstraction for fetching these values. Since `ThisAssembly` exists I was intending to centralize on it.

It does limit my extension to only projects that leverage nbgv but that's not an issue for us: the extension is not public, and we want to standardize versioning on all projects in the company to rely on the same mechanism.

**Comment by AArnott** [comment]
> why does ThisAssembly exist in the first place if we can already gather the information from the attributes as well?

To avoid reflection when an assembly needs its own information at runtime. It's both a perf and syntax optimization. But reading this data from outside the assembly, you couldn't avoid reflection anyway, and I'll guess that the perf difference from avoiding a *few* of those reflection calls in your scenario is insignificant.

The single authority on versioning is traditionally the assembly attributes. Is there any information in `ThisAssembly` that is _not_ in the attributes that you need? If so, can you share which data you need and we can talk about possibly adding an attribute for it?

**Comment by julealgon** [comment]
> To avoid reflection when an assembly needs its own information at runtime. It's both a perf and syntax optimization. 

I see, fair enough.

> But reading this data from outside the assembly, you couldn't avoid reflection anyway, and I'll guess that the perf difference from avoiding a _few_ of those reflection calls in your scenario is insignificant.

It definitely is insignificant. I wasn't pursuing this for performance reasons but for consistency.

> Is there any information in `ThisAssembly` that is _not_ in the attributes that you need? If so, can you share which data you need and we can talk about possibly adding an attribute for it?

As of now, I was focusing on just the app name and version, so no: I can fetch both from assembly attributes directly.

> The single authority on versioning is traditionally the assembly attributes. 

Fair enough. If that's the case, I'll just rely on the attributes themselves and make this extension more general.

**Comment by julealgon** [comment]
> @julealgon do you want to read the version information from assemblies maintained by your company, or from third-party assemblies that you cannot modify?

From company-controlled assemblies only @KalleOlaviNiemitalo . This is an internal extension meant to be used by other teams in their APIs/services.

**Comment by julealgon** [comment]
> * It provides some information that is not normally available from attributes, such as the Git commit timestamp. Although I suppose you could easily stash those in AssemblyMetadataAttribute if you wanted.

@AArnott I know this is an old one and already closed, but more recently I've started to also need this git commit value to push source information in my telemetry, mainly for source code integration with Datadog.

Do you think the library could also store this git commit in a `AssemblyMetadataAttribute` like @KalleOlaviNiemitalo mentionedthat the code could then read using reflection? This is going to start to become a problem for us as we try to extract that git commit resource population into a reusable library, since, as we discussed, `ThisAssembly` is only visible by the project itself.

**Comment by AArnott** [comment]
You can certainly do that. AssemblyMetadataAttribute's can be added by msbuild, and msbuild has access to the git commit properties that NB.GV sets. 

Here are some docs to get you started:
https://dotnet.github.io/Nerdbank.GitVersioning/docs/build-systems/msbuild.html
https://learn.microsoft.com/en-us/dotnet/standard/assembly/set-attributes-project-file#set-arbitrary-attributes

**Comment by julealgon** [comment]
I was mostly aware of that @AArnott , but my question was more about having the `NerdBank.GitVersioning` NuGet package itself do it.

Don't you think it would make sense?

**Comment by AArnott** [comment]
I wouldn't be opposed to it, but I wouldn't run into it without at least two independent people/codebases wanting it.
