### ISSUE TITLE
Why does GenerateAssemblyNBGVVersionInfo set UltimateResourceFallbackLocation?

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/Nerdbank.GitVersioning#790]
The GenerateAssemblyNBGVVersionInfo target sets the UltimateResourceFallbackLocation property here:

<https://github.com/dotnet/Nerdbank.GitVersioning/blob/1aa8ea6a44072ac40d9a51b12d037ca66630f9c4/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L119>

I'm curious why it does that. The UltimateResourceFallbackLocation property is not referenced elsewhere in the dotnet/Nerdbank.GitVersioning repository (not even in the commit history), and it does not affect how [the GetAssemblyAttributes target generates NeutralResourcesLanguageAttribute](https://github.com/dotnet/sdk/blob/dc262f0c444d57181e580d4d5b9a517ea558c64a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L106-L108).

<details><summary>(What I was doing when I noticed this)</summary>
I was looking for ways to generate an AssemblyMetadataAttribute for GitCommitDate. I found that I can do it with a custom target:

```XML
<Target Name="AddAssemblyMetadataForGitCommitDate" BeforeTargets="GetAssemblyAttributes" DependsOnTargets="GetBuildVersion">
  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
      <_Parameter1>GitCommitDate</_Parameter1>
      <_Parameter2>$([System.DateTime]::new($(GitCommitDateTicks)).ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'Z'"))</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
</Target>
```

This creates an AssemblyAttribute item rather than an AssemblyMetadata item, so as not to depend on <https://github.com/dotnet/sdk/issues/3166>, which was implemented in .NET SDK 5.0.100.

Because Git commit timestamps include time zone offset information, I feel DateTimeOffset would be a more suitable type than DateTime, but the offset doesn't seem to be available from Nerdbank.GitVersioning. However, I'm planning to use this for the SARIF-v2.1.0 §3.19.15 releaseDateUtc property, which requires UTC anyway.
</details>

**Comment by AArnott** [comment]
No idea. Except that that xml fragment matches something in one of our internal repos, so somehow one was likely copied from the other. I'm not sure which direction it went -- probably from here to there. But this has _nothing_ to do with versioning, and as you say nothing seems impacted by it. I'll remove it.
