### ISSUE TITLE
Incorrect height in PR?

### ISSUE THREAD

**Issue by flobernd** [dotnet/Nerdbank.GitVersioning#796]
Hi there,

maybe it's just me not fully understanding the Git height metric, but in my case I have a version `1.2.2` released on `master`. If I create a PR with just a single commit, running `nbgv get-version` in the CI shows `1.2.4`.

No other commit has been pushed to `master` in the meantime either.

Is there an explaination for this?

**Comment by flobernd** [comment]
@KalleOlaviNiemitalo 

Ah right, that might be the reason. I'm using the GitHub "checkout" action. This one seems to check out the actual merge commit instead of the branch (results in a detached HEAD as well).

I guess I have to conditionally modify the 'version.json' to subtract 1 from the height. Otherwise my CI artifacts will have different version numbers than the resulting release on 'master'.

Maybe it's even worth a discussion, if this should be the default for PRs on GitHub. It's kinda confusing this way.

**Comment by flobernd** [comment]
> Why, do you make squash merges?

Sometimes you want to have more verbose commits for review, but only a big commit when merging the final feature to master.

I like linear git history in general. Usually I rebase, but sometimes when there are multiple bug fix commits e.g. after an initial PR review, I'm going for squash.

**Comment by AArnott** [comment]
> Well, at the end I can't know if the PR is going to be merge, rebase or squash committed. Guess I have to life with that behavior :-)

+1 to that. Rebase, merge or squash will all result in unique git heights. And even if you always merged, there's no guarantee that after your PR is merged that the height will be the same, because your target branch may have accepted other PRs and thus have a larger height than the provisionary merge commit created by your own PR.
