### ISSUE TITLE
The target "GetTargetPath" does not exist in the project

### ISSUE THREAD

**Issue by jmelosegui** [dotnet/Nerdbank.GitVersioning#820]
Hi @AArnott, 
I am using this tool in a solution that contains a SqlServer project.
When building the database project, I receive the following error.

##[error]packages\nerdbank.gitversioning\3.5.109\build\PrivateP2PCaching.proj(0,0): Error MSB4057: The target "GetTargetPath" does not exist in the project.

If I modify the file `PrivateP2PCaching.proj` by adding the following

```
  <!-- database project wants to see this target -->
  <Target Name="GetTargetPath" />
```
The solution builds successfully.

I am not sure of the implication of this change.

The following are the logs for the failing build using [msbuild structured log](https://msbuildlog.com/).

[msbuild.binlog.zip](https://github.com/dotnet/Nerdbank.GitVersioning/files/9609625/msbuild.zip)

Is this something you can look into?

I really appreciate any help you can provide.

### Update
I was using version [3.5.109](https://www.nuget.org/packages/Nerdbank.GitVersioning/3.5.109). If I downgrade the version to [3.4.255](https://www.nuget.org/packages/Nerdbank.GitVersioning/3.4.255), where the file `PrivateP2PCaching.proj` is not part of the referenced projects, then the build process ends successfully.

**Comment by AArnott** [comment]
Thanks for reporting.
