### ISSUE TITLE
GitVersioning not creating branch on prepare-release

### ISSUE THREAD

**Issue by GurdipS5** [dotnet/Nerdbank.GitVersioning#823]
Hi,
I am using GitVersioning with a .NET Core project for the first time. However, when running the prepare-release command, I don't see a branch created?

Also, I'd like to increment version per commit, just to confirm, this is possible?

**Comment by AArnott** [comment]
NB.GV definitely increments the version per commit. That's its core feature.

Can you prepare a full repro for your case of `prepare-release` not creating a branch? I think it won't create a branch if the branch it would create already exists. I can't think of any other case.

**Comment by GurdipS5** [comment]
Hi,
Thanks for the quick reply. I didn't realise I had changes staged to source control so that's why I had no branch made, so no issues!

The increment per commit is great as I need that for Octopus Deploy. I have setup the build server to use this (presumalby teamcity writes to build.number). and will do a test build soon.
