### ISSUE TITLE
IsContentOfFilesTheSame assumes full Stream.Read

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/Nerdbank.GitVersioning#825]
In the  Nerdbank.GitVersioning.Tasks.CompareFiles class, the IsContentOfFilesTheSame method calls Stream.Read and assumes that a return value smaller than requested means that it got to the end of the file. As mentioned in <https://github.com/dotnet/Nerdbank.GitVersioning/issues/797#issuecomment-1251251500>, such an assumption is generally a bug. Here though, the stream refers to a regular file, which makes the assumption more likely to hold.

<https://github.com/dotnet/Nerdbank.GitVersioning/blob/719b0d50b809aece0f2c82d3ee27b2829dab4224/src/Nerdbank.GitVersioning.Tasks/CompareFiles.cs#L127-L133>

The CompareFiles task is used in Nerdbank.GitVersioning.targets, for deciding whether to run the Copy task. The bug might cause the task to consider the files different when they are actually identical; the target would then needlessly copy the file and cause MSBuild to execute other targets, resulting in a slower incremental build but eventually the correct artefacts.

It might be possible to delete the CompareFiles task altogether and use the SkipUnchangedFiles parameter of the Copy task instead.

<https://github.com/dotnet/Nerdbank.GitVersioning/blob/a908c6d9d2ed9b032d63ff885b4ccc97fc32046d/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L144-L149>
<https://github.com/dotnet/Nerdbank.GitVersioning/blob/a908c6d9d2ed9b032d63ff885b4ccc97fc32046d/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L181-L186>

**Comment by AArnott** [comment]
Thanks for finding the bug. It turns out that `Copy.SkipUnchangedFiles` employs a cheap trick (probably for perf reasons) and [will assume that the files are different when the timestamp is different](https://github.com/dotnet/msbuild/blob/c7d758591e31a066212058d589759c580336deff/src/Tasks/Copy.cs#L722), so it defeats the incremental build preservation that I'm attempting to do. I'll have to fix my task.
