### ISSUE TITLE
Versioning issue with MAUI

### ISSUE THREAD

**Issue by espenrl** [dotnet/Nerdbank.GitVersioning#828]
Using `Nerdbank.GitVersioning` together with MAUI is not that easy with regards to setting `ApplicationVersion` and `ApplicationDisplayVersion` properties. The main problem is setting the properties after `Nerdbank.GitVersioning` has exceuted, but before generating the manifests for Android, iOS and Windows.

The following code takes care of all this, and also adheres to the versioning requirements for each platform. The targets `FixVersionFor*` will make sure `SetApplicationVersion` is executed at the right time in the MSBuild pipeline.

NOTE: This code only takes care of Android, iOS and Windows.

``` xml
    <Target Name="FixVersionForAndroid"
            Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'"
            BeforeTargets="_GetAndroidPackageName"
            DependsOnTargets="SetApplicationVersion" />

    <Target Name="FixVersionForIOS" 
            Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'"
            BeforeTargets="_CompileAppManifest"
            DependsOnTargets="SetApplicationVersion" />

    <Target Name="FixVersionForWindows" 
            Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'" 
            BeforeTargets="MauiGeneratePackageAppxManifest" 
            DependsOnTargets="SetApplicationVersion" />

    <Target Name="SetApplicationVersion" DependsOnTargets="GetBuildVersion">

        <PropertyGroup>
            
            <_MajorStr>$([System.String]::Format("{0}", $([System.Version]::Parse("$(BuildVersion)").Major)))</_MajorStr>
            <_MinorStr>$([System.String]::Format("{0:D2}", $([System.Version]::Parse("$(BuildVersion)").Minor)))</_MinorStr>
            <_BuildStr>$([System.String]::Format("{0:D3}", $([System.Version]::Parse("$(BuildVersion)").Build)))</_BuildStr>

            <!-- Android requirement: ApplicationVersion must be a positive integer (used as an internal version number) -->
            <!-- iOS requirement: ApplicationVersion must be a three part version number -->
            <!-- Windows requirement: ApplicationVersion must be blank when ApplicationDisplayVersion is a four part version number -->
            <ApplicationVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">$(_MajorStr)$(_MinorStr)$(_BuildStr)</ApplicationVersion>
            <ApplicationVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">$(BuildVersionSimple)</ApplicationVersion>
            <ApplicationVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'"></ApplicationVersion>

            <!-- iOS requirement: ApplicationDisplayVersion must be a three part version number -->
            <!-- Windows requirement: ApplicationDisplayVersion must be a four part version number -->
            <ApplicationDisplayVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">$(Version)</ApplicationDisplayVersion>
            <ApplicationDisplayVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">$(BuildVersionSimple)</ApplicationDisplayVersion>
            <ApplicationDisplayVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">$(BuildVersion)</ApplicationDisplayVersion>

        </PropertyGroup>

    </Target>
```

**Comment by espenrl** [comment]
Resources I used to learn about all this.

| Property                  | Android                                                                               | iOS                                                                                                                                          |
| ------------------------- | ------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------- |
| ApplicationId             | package                                                                               | [CFBundleIdentifier](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier)                 |
| ApplicationVersion        | [android:versionCode](https://android-doc.github.io/tools/publishing/versioning.html) | [CFBundleVersion](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion)                       |
| ApplicationDisplayVersion | [android:versionName](https://android-doc.github.io/tools/publishing/versioning.html) | [CFBundleShortVersionString](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring) |

- Android
  - https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
- iOS
  - https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.MacDev.Tasks/Tasks/CompileAppManifestTaskBase.cs
  - https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.Shared/Xamarin.Shared.targets
- Windows
  - https://github.com/dotnet/maui/blob/main/.nuspec/Microsoft.Maui.Resizetizer.targets

**Comment by AArnott** [comment]
Why use the msbuild intrinsic method when `$(targetplatformidentifier)` exists as a property?

**Comment by AArnott** [comment]
Does the `ApplicationVersion` show up anywhere for Android such that being human readable is useful? The reason I ask is your method of creating 102003 fails to guarantee incrementing integers when the build number exceeds 999 or the minor version exceeds 99. But if we instead assign the major version to the 1st byte of the integer, minor to the second byte, and the build number to the 3rd and 4th bytes, then the major version can reach 128, minor can reach 255, and the build number can reach 65535 before an overflow screws things up.

**Comment by espenrl** [comment]
The scheme I've chosen is quite rudimentary and I would be happy to find a better solution.

The version code is basically there to protect of app downgrades, so it is important for the integer to be monotonic increasing for successive versions.

From https://developer.android.com/studio/publish/versioning

> versionCode — A positive integer used as an internal version number. This number is used only to determine whether one version is more recent than another, with higher numbers indicating more recent versions. This is not the version number shown to users; that number is set by the versionName setting, below. The Android system uses the versionCode value to protect against downgrades by preventing users from installing an APK with a lower versionCode than the version currently installed on their device.
The value is a positive integer so that other apps can programmatically evaluate it, for example to check an upgrade or downgrade relationship. You can set the value to any positive integer you want, however you should make sure that each successive release of your app uses a greater value. You cannot upload an APK to the Play Store with a versionCode you have already used for a previous version.

> Note: In some specific situations, you might wish to upload a version of your app with a lower versionCode than the most recent version. For example, if you are publishing multiple APKs, you might have pre-set versionCode ranges for specific APKs. For more about assigning versionCode values for multiple APKs, see [Multiple APK Support](https://developer.android.com/google/play/publishing/multiple-apks#VersionCodes).

> Typically, you would release the first version of your app with versionCode set to 1, then monotonically increase the value with each release, regardless of whether the release constitutes a major or minor release. This means that the versionCode value does not necessarily have a strong resemblance to the app release version that is visible to the user (see versionName, below). Apps and publishing services should not display this version value to users.

> Warning: The greatest value Google Play allows for versionCode is 2100000000.

Thanks for the `$(TargetPlatformIdentifier)` tip, Andrew.

**Comment by AArnott** [comment]
Great. Thanks for the confirmation. I'm about ready to send out a PR for this. I'd very much appreciate your validation that it works for you, as I don't have any maui projects to play with.

**Comment by espenrl** [comment]
I tested `3.6.58-alpha` and it looks good. Here is the details of the Android APK.

![image](https://user-images.githubusercontent.com/4621581/197369087-2ca5231b-521f-4cbf-943b-b80a3706ce74.png)

**Comment by espenrl** [comment]
Great feedback Bryan. As to how an opt-in or opt-out mechanism would work - I think it's best for @AArnott to answer.

**Comment by bakerhillpins** [comment]
Another thing to note as I've continued to include these changes into my CI/CD systems.  MAUI makes Application Information (including versions/build no) available to users through a static Class called [AppInfo](https://github.com/dotnet/maui/blob/900d5f757567ac0a398772474e91cb406d7cb29c/src/Essentials/src/AppInfo/AppInfo.shared.cs#L28) which is really just a redirect into a platform specific implementation of [IAppInfo](https://github.com/dotnet/maui/blob/900d5f757567ac0a398772474e91cb406d7cb29c/src/Essentials/src/AppInfo/AppInfo.shared.cs#L6) for use with the Service discovery/DI functionality.  The platform specific implementations read and convert the Version/VersionString/BuildNo elements that nb.gv is updating as you can see here in the [Android implementation](https://github.com/dotnet/maui/blob/900d5f757567ac0a398772474e91cb406d7cb29c/src/Essentials/src/AppInfo/AppInfo.android.cs#L12).  The issue that I'm currently experiencing is that the `AppInfo.Version` property (redirect to the `IAppInfo.Version`) derives from the `IAppInfo.VersionString` property. The nb.gv results of course are more complex than a basic semantic version string. E.g. `0.1.23-beta-g030726a954`. However, MAUI as it stands today makes a [relatively simplistic approach](https://github.com/dotnet/maui/blob/900d5f757567ac0a398772474e91cb406d7cb29c/src/Essentials/src/Types/Shared/Utils.shared.cs#L10) at decoding a version string and as such the nb.gv VersionString which frequently goes beyond a dotted triple/quad reverts to the default of 0.0. 

This is a solvable problem for those of us using nb.gv, we'd simply need to write a more complex parsing algo and wrap the IAppInfo implementation for use in our systems if so desired, or possibly just use the `VersionString` Property. Not a huge issue but something that I encountered and didn't immediately realize when I noted that the `IAppInfo.Version` property "wasn't working".

**Comment by AArnott** [comment]
> In other words, for macOS apps you cannot use the same build numbers again in different release trains. iOS apps have no such restriction and you can re-use the same build numbers again in different release trains

I don't know what a release train is.

> would almost prefer a soft switch to disable or otherwise check if it's on the command line.

Checking for a global property set as a CLI switch is impossible. But we can add another property to suppress setting these.

> Of course another solution is to not reference the nb.gv package for the App Exe project but that defeats the convenience of Directory.Build.props including it in all your projects globally.

What you could do is add a condition to the `PackageReference` based on a property that you can set in the exe project, making it on by default but omittable by setting some `<NoNBGVHere>true` property in your exe project file.

> As to how an opt-in or opt-out mechanism would work - I think it's best for @AArnott to answer.

I think we should define one property that can deactivate the setting of Maui properties. I'll prepare a change.

**Comment by bakerhillpins** [comment]
> > In other words, for macOS apps you cannot use the same build numbers again in different release trains. iOS apps have no such restriction and you can re-use the same build numbers again in different release trains
> 
> I don't know what a release train is.

It's described in the Apple Tech bulletin linked. [Apple for iOS/MacOS](https://developer.apple.com/library/archive/technotes/tn2420/_index.html)

> Checking for a global property set as a CLI switch is impossible. But we can add another property to suppress setting these.

So I'm assuming one could set this new property from the CLI correct?
 
> What you could do is add a condition to the `PackageReference` based on a property that you can set in the exe project, making it on by default but omittable by setting some `<NoNBGVHere>true` property in your exe project file.

I'll have to try that and report back.
 
> > As to how an opt-in or opt-out mechanism would work - I think it's best for @AArnott to answer.
> 
> I think we should define one property that can deactivate the setting of Maui properties. I'll prepare a change.

I'll try this change tomorrow. I commented in the PR. Thanks!

**Comment by AArnott** [comment]
> So I'm assuming one could set this new property from the CLI correct?

Yes, or in the project file.

**Comment by Axemasta** [comment]
@bakerhillpins did your project end up adopting the code as you showed above?

I'm trying to run a similar setup myself, I've found if I simply try to set the values:
```xml
<PropertyGroup>
    <NBGV_SetMauiVersionProperties>false</NBGV_SetMauiVersionProperties>
    <ApplicationVersion>$(BuildVersionSimple)</ApplicationVersion>
    <ApplicationDisplayVersion>$(BuildVersionSimple)</ApplicationDisplayVersion>
</PropertyGroup>
```
This doesn't work, however if I copy the NBGV targets for each platform it will work:

```xml
<PropertyGroup>
    <NBGV_SetMauiVersionProperties>false</NBGV_SetMauiVersionProperties>
</PropertyGroup>
    
<Target Name="SetVersionForMauiIOS"
        Condition="'$(TargetPlatformIdentifier)' == 'ios' or '$(TargetPlatformIdentifier)' == 'maccatalyst'"
        BeforeTargets="_CompileAppManifest"
        DependsOnTargets="GetBuildVersion">
    <PropertyGroup>
        <ApplicationVersion>$(BuildVersion)</ApplicationVersion>
        <ApplicationDisplayVersion>$(BuildVersionSimple)</ApplicationDisplayVersion>
    </PropertyGroup>
</Target>
```

Unsure as to what is going wrong, I can workaround it in the meantime but quite inelegant / inflexible as I want the same git version (maj.min.patch) across all my platforms and set the build number from my cloud agent.

**Comment by bakerhillpins** [comment]
@Axemasta Alex. this was 2 yrs ago and going back to look at that project now I don't see anything where we're disabling the NBGV. It's a stale project at the moment (it was shelved). While it builds I don't have the time to go back and dig into it.  Sorry.

If you look at the other issues/PRs linked to this one it might help you understand the current state of this feature because I know it moved a bit.
