### ISSUE TITLE
version.schema.json is UTF-8 with BOM, VSCode expects no BOM

### ISSUE THREAD

**Issue by amis92** [dotnet/Nerdbank.GitVersioning#839]
### Description

Visual Studio Code complains that the `version.schema.json` file contains a BOM, when referencing `https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/main/src/NerdBank.GitVersioning/version.schema.json` as `$schema`.

### Impact

Currently, just a warning squiggle is shown, but the schema is correctly resolved and intellisense works.
I do not know whether this will work in future, but for now it's just irritating to see warnings when everything is actually fine.

![image](https://user-images.githubusercontent.com/2671396/195850432-19fff38b-7b92-4413-b48d-11cb50c4c47d.png)

### Suggested Solution

Remove BOM from the `version.schema.json`. It shouldn't negatively impact any tooling.

**Comment by AArnott** [comment]
Thanks for investigating and fixing this. I have seen the warning squiggle in VS Code many times but never hovered over it to discover what exactly it was complaining about. 
I don't object to the fix, but I think it's super lame that VS Code complains about this (even though it is actually supported), so I'll file a bug against VS Code too.

**Comment by AArnott** [comment]
Filed https://github.com/microsoft/vscode/issues/163683.
