### ISSUE TITLE
Always NonShippable for all branches

### ISSUE THREAD

**Issue by russosalv** [dotnet/Nerdbank.GitVersioning#842]
with configuration 
```
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.0.0-ci.{height}",
  "inherit": true,
  "publicReleaseRefSpec": [
      "^refs/heads/main",
	  "^refs/heads/develop",
	  "^refs/heads/feature\/\\d+"
    ],
  "pathFilters": [
    "./"
  ]
}
```

when build also if i'm in Main or develop or feature/blablabla

the package is NonShippable

**Comment by AArnott** [comment]
I assume by non-shippable you mean that the PublicRelease=false, and you get a git commit and the end of the version. 

Your `feature` branch spec looks wrong, for one thing. It would match `feature/35`, but not `feature/blablabla`. And you have an extra escape character too. As a nit, you're also missing the `$` character, so `main123` would also be considered a public release branch.

I would fix it up like this:

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.0.0-ci.{height}",
  "inherit": true,
  "publicReleaseRefSpec": [
    "^refs/heads/main$",
    "^refs/heads/develop$",
    "^refs/heads/feature/"
  ],
  "pathFilters": ["./"]
}
```

That said, I took your file just as is (minus the `inherit`) and put it into one of my repos, and my `main` branch built as a public release just fine. So it's not clear to me why it wouldn't work in your repo. What symptoms do you see that suggest you're not building a public release? Is this observable in local builds, or in some kind of cloud build?
