### ISSUE TITLE
Service Fabric Support

### ISSUE THREAD

**Issue by AlexEyler** [dotnet/Nerdbank.GitVersioning#845]
Hi,

Is versioning an sfproj supported by Nerdbank.GitVersioning? It doesn't appear to work on the latest package version (3.5.113).

**Repro steps**
1. Create a new service fabric project
2. Manage nuget packages on sln > add Nerdbank.GitVersioning to sfproj
3. For some reason, that doesn't actually add the imports for the props and targets, so manually update the sfproj to import Nerdbank.GitVersioning.props/targets
4. Build the solution

**Expected**
Build succeeds

**Actual**
Build fails with error similar to:
> 'C:\s\personal\Application1\packages\Nerdbank.GitVersioning.3.5.113\build\PackageRoot\ServiceManifest.xml' does not exist.	Application1

**Version info:**
* Nerdbank.GitVersioning: 3.5.113
* Microsoft.VisualStudio.Azure.Fabric.MSBuild: 1.7.6 

**Analysis**
When I look more closely, it looks like the GetServiceProjectReferences target in Microsoft.VisualStudio.Azure.Fabric.Application.targets is the one that fails. It appears to require that all project references from the sfproj contain a ServiceManifest.xml file somewhere underneath its project directory, and there doesn't appear to be a way to filter the project references before the target is called. Nerdbank.GitVersioning seems to add a project reference (`$(NerdbankPackagePath)/build/PrivateP2PCaching`) to the project being versioned, so it causes the sfproj build to fail.

Is there a way around this? I'd like to use the build version to set the application version as well, if it's possible.

**Comment by AlexEyler** [comment]
Adding `<NBGV_CacheMode>None</NBGV_CacheMode>` seems to resolve the issue because it prevents the project from being added to the ProjectReference item.

**Comment by AArnott** [comment]
SF application projects don't appear to produce a build output of their own, so adding NB.GV as a package reference to it doesn't appear to be useful, FWIW.
