### ISSUE TITLE
Building a docker container using Nerdback.GitVersioning - missing properties on ThisAssembly

### ISSUE THREAD

**Issue by TheCakeMonster** [dotnet/Nerdbank.GitVersioning#854]
This is an issue that I am logging as documentation for anyone else who has the same problem.

I've had a problem with building a project that uses Nerdbank.GitVersioning where we were using the project to build a docker container. The code in the project made use of the ThisAssembly class auto-generated by NBGV to access the GitCommitId property. The project built in Visual Studio and at the command line, but failed when building the docker container with the message

'ThisAssembly' does not contain a definition for 'GitCommitId'

The source code of Nerdbank.GitVersioning indicated that the property was only output when it has a value, and that's the clue to the problem; NBGV was unable to determine the git commit details.

**Comment by TheCakeMonster** [comment]
I should point out that the downside to changing .dockerignore in this way is that the git repo could be included in the end image. That makes the image bigger than it should be, and could expose sensitive information that was within the repo. This is far from ideal.

**Comment by AArnott** [comment]
@TheCakeMonster Thanks for the feedback and your result.

FYI we have a section on [docker documented](https://github.com/dotnet/Nerdbank.GitVersioning/blob/dc0a8cfe732e7e589836225666b81e1b7ef58d82/doc/cloudbuild.md#docker-build), but it doesn't discuss the issue you're hitting. But I think [this issue comment](https://github.com/dotnet/Nerdbank.GitVersioning/issues/416#issuecomment-567778587) does. Can you check it out? If it addresses your concern, we can add it the docker document.
