### ISSUE TITLE
Swap major version?

### ISSUE THREAD

**Issue by virzak** [dotnet/Nerdbank.GitVersioning#877]
An [EF Core Window Functions library](https://github.com/zompinc/efcore-extensions) I maintain depends on EF Core 6 and EF Core 7, both of which run TFM 6, since it is LTS.

What most extension libraries do in this case is: produce 2 versions of their library (e. g. 6.0.424 and 7.0 424).

I overrode package version as per https://github.com/dotnet/Nerdbank.GitVersioning/issues/731#issuecomment-1157223604. Here is the commit: https://github.com/zompinc/efcore-extensions/commit/c0c3c6b127ba78bee9f41726fedf1ef4808b900a

The resulting nuget packages have the correct 6 and 7 versions, but the DLL AssemblyFileVersion and others were not overridden.

Is it possible to override the major version for everything?

Previous to this, the library was multitargeted, until an [issue](https://github.com/zompinc/efcore-extensions/issues/4) was filed that Window Functions for  EF Core 7 version didn't work with .NET 6.

**Comment by AArnott** [comment]
I'm glad you found my comment that documents how to do this. That comment only presents overriding the `PackageVersion` property in the example, but there are [a slew of other properties you can also override](https://github.com/dotnet/Nerdbank.GitVersioning/blob/274a42ed3321bcc43632dc970d65677f99a486a9/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L121-L142), all of which feed into AssemblyInfo attributes so you can override those and get what you want as well.

**Comment by virzak** [comment]
Awesome, thanks! That answers it :)
