### ISSUE TITLE
How to use Nerdbank.GitVersioning with our workflow

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/Nerdbank.GitVersioning#895]
The world of builds and CI is far beyond my realm of daily work - I apologize for my lack of knowledge.

Our team maintains a desktop app (WPF) for a company. We create builds (releases?) for `QA`,`UAT`, and `Prod`.  Our workflow is that developers work off feature branches, create PR's, which are merged to main when approved.  

After some number of features are complete we release a `QA` build by creating a git tag off main branch in the format `QA/tagname`.  The creation of the tag kicks off a CI build (Azure pipelines).  The resulting binaries are droped on a server in a folder named `QA/tagname`.  Tagnames can be anything but our standard is to use the current date: `QA/230218`.

The preceding is mostly true for `UAT` and `Prod`.  `UAT` tags are based on `QA` tags and `Prod` tags are based on `UAT` or `QA`.  

This simple workflow works well for us.  It is mostly effortless - the missing piece is that we have no way of versioning binaries. 

Having read [Using the nbgv .NET Core CLI tool](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/nbgv-cli.md#preparing-a-release) it is not clear to me how we can map the process above into how `nbgv` works.  We have some degree of latitude in how builds are created and will make every effort to use a workflow that maximizes the utility of `nbgv`.  We would like to continue the use of folder names that match the version number because our QA team often goes back to prior builds to test one against the other.

We like the use of tags vs branches for builds - we had to work very hard to get our release management group to use them. Our only must-have is that a developer must be able to directly map an assembly version to a tag (or, less preferably, a branch).

[Reference](https://ml-software.ch/posts/versioning-made-easier-with-nerdbank-gitversioning)

**Comment by AArnott** [comment]
> the missing piece is that we have no way of versioning binaries

Can you add the Nerdbank.GitVersioning package to your msbuild projects? That, plus a version.json file, will handle versioning of the binaries. The `nbgv` CLI tool isn't necessary at that point. 

I have no concern with your use of `QA/date` as your tag name pattern. Do you? Are you looking to change it to `QA/1.3.5` to match the version that the binaries are stamped with? If so, `nbgv tag` may help you. The upcoming 3.6 version adds a version.json property where you can even set the tag name pattern to start with `QA/` instead of the default `v`. 
Alternatively you can keep creating your own tag names, but use `nbgv` to give you the version element. For example, this powershell command will create a tag for you with your custom pattern:
```
git tag "QA/$((nbgv get-version -f json | convertfrom-json).SimpleVersion)"
```

**Comment by sam-wheat** [comment]
Hi Andrew, thanks for responding.

The only msbuild projects we use are the application Visual Studio .csproj files. I have to check with our RM team but I think the short answer is yes we can add Nerdbank.GitVersioning package to that.  We also use an Azure CICD pipeline.

We can change the tag name to be the version and probably should.  The only caveat is that we need to create a tag to generate a build and the version is not known at that time.  I suppose part of pipeline could be to create a new tag with the version and delete the one that kicked off the build.  If we do that, is there a way to maintain source tag history when promoting a build to the next environment?

We will definitely want the QA/UAT/Prod prefix on the tag.  Will the code example you provided only work on 3.6?

**Comment by AArnott** [comment]
> The only caveat is that we need to create a tag to generate a build and the version is not known at that time. 

If it's based on the version, you _do_ know it at queue time. NB.GV is all about deterministic versions. You know what the version is whether it's local or in the cloud, because the commit determines the version, not the clock.

> Will the code example you provided only work on 3.6?

No. The code sample works today with 3.5.
