### ISSUE TITLE
How to set version property from CLI?

### ISSUE THREAD

**Issue by sengiv** [dotnet/Nerdbank.GitVersioning#907]
> **Working**

![image](https://user-images.githubusercontent.com/43817262/224366140-70a54dbd-615e-4d17-b510-7aa268c3d958.png)

> **Error**

![image](https://user-images.githubusercontent.com/43817262/224367121-ae38f26d-08f2-453d-9b88-a8a41619b0a7.png)

### How to only set a specific property like `PrereleaseVersion`?
![image](https://user-images.githubusercontent.com/43817262/224362636-2146b7ca-08ea-4067-939c-7ff3bcc4f28c.png)

### Use case:
Normally would edit `version.json` but our build tool needs to take 1 repo and stamp it & deploys to 2 places, so have to automate. If [Nerdbank.GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning) can't do this, then next choice is to modify `version.json` via 3rd party tool

**Comment by AArnott** [comment]
The `PrereleaseVersion` isn't its own property in version.json. If you want to set the prerelease, just go ahead and do it with the original command:
`nbgv set-version 3.6.100-preview.2`
