### ISSUE TITLE
deps.json of reference project is not generated during publish 

### ISSUE THREAD

**Issue by ffalsino** [dotnet/Nerdbank.GitVersioning#910]
Hello,

I created two WPF Project:
- TestDashboard
- TestFrame

TestDashboard has a reference to the project TestFrame.

If I not use Nerdbank.GitVersioning package during the build process the deps.json is created like this:
```json
{
  "targets": {
    ".NETCoreApp,Version=v6.0": {},
    ".NETCoreApp,Version=v6.0/win10-x64": {
      "TestDashboard/1.0.0": {
        "dependencies": {
          "TestFrame": "1.0.0",
          "TestFrame.Reference": "1.0.0.0"
        }
      },
      "TestFrame/1.0.0": {
        "runtime": {
          "TestFrame.dll": {}
        }
      },
      "TestFrame.Reference/1.0.0.0": {
        "runtime": {
          "TestFrame.dll": {
            "assemblyVersion": "1.0.0.0",
            "fileVersion": "1.0.0.0"
          }
        }
      }
    }
  }
}
```

Then If I publish the TestDashboard, in the publish folder the deps.json file are correctly generated: TestDashboard.deps.json and TestFrame.deps.json.

When  Nerdbank.GitVersioning package it is used, during the build process the deps.json is generated like this:
```json
{
  "targets": {
    ".NETCoreApp,Version=v6.0": {},
    ".NETCoreApp,Version=v6.0/win10-x64": {
      "TestDashboard/10.2.0-pre-g": {
        "dependencies": {
          "TestFrame": "1.0.0",
          "Nerdbank.GitVersioning": "3.5.119",
          "TestFrame.Reference": "10.2.0.0"
        }
      },
      "TestFrame/1.0.0": {
        "runtime": {
          "Daimler.ITF.Jule.Client.Frame.dll": {}
        }
      },
      "TestFrame.Reference/10.2.0.0": {
        "runtime": {
          "TestFrame.dll": {
            "assemblyVersion": "10.2.0.0",
            "fileVersion": "10.2.0.0"
          }
        }
      }
    }
  }
}
```

Then If I publish the TestDashboard, in the publish folder only TestDashboard.deps.json is generated and **TestFrame.deps.json is not generated.**

The version.json is:
```json
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "10.2-pre",
  "versionHeightOffset": -1,
  "publicReleaseRefSpec": [
    "^refs/heads/master$",
    "^refs/heads/release/\\d+\\.\\d+\\.\\d+"
  ],
  "assemblyVersion": {
	"precision": "revision"
  },
  "release": {
    "branchName": "release/{version}",
    "versionIncrement": "minor",
    "firstUnstableTag": "pre"
  },
  "cloudBuild": {
    "setVersionVariables": false
  }
}
```

Could you please help me with this issue?

**Comment by AArnott** [comment]
I have no idea how NB.GV could be impacting the .deps.json publishing. It certainly isn't supposed to have that effect.

The way to investigate this would be to build with the `/bl` switch, both in the working case and the broken case, and then compare the binlogs to see what produces the .deps.json when it works, and then look at what conditions were not met in the broken binlog that prevented publishing the file. Then backtrack from there to see how NB.GV influenced those conditions.

If you find out why, I'd be happy to take a look. Or if you can send me a small zip that repros the problem, I may be able to find time to investigate myself, but I can't promise anything.

**Comment by ffalsino** [comment]
Hi,
Thank you so much for your reply.
I tried to take a look at these binlog generated, but I didn't figure out where is the problem. Seems that some Task before the Publish, remove the item deps.json, so the Publish Task copy the items without the deps.json referenced.

If you want to take a look I attach the project here and also the two bin logs:
[deps-json-publish-issue.zip](https://github.com/dotnet/Nerdbank.GitVersioning/files/11006824/deps-json-publish-issue.zip)

Note:
As the build works correctly, I mean, the deps.json files are correctly generated, I attached the binlogs related to the publish with this command:
`dotnet publish -bl:c:\logs\pubishwrong.binlog TestDashboard\TestDashboard.csproj -c Release -r win10-x64 --self-contained true --output TestDashboard\bin\Release\publishcmd`

**Comment by ffalsino** [comment]
I don't think this issue is related to Nerdbank.GitVersioning library.
I tried by removing PrivateAssets tag to PackageReference, and deps.json files are correctly generated.
```json
<Project>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning">
      <Version>3.5.119</Version>
    </PackageReference>
  </ItemGroup>
</Project>
```

**Comment by AArnott** [comment]
Given a change to `PrivateAssets` influences the outcome, and the other evidence we have, I agree with you that this isn't related to NB.GV. Can you take this up with [the .NET SDK folks](https://github.com/dotnet/sdk)?
