### ISSUE TITLE
build.ps1 references src\Nerdbank.GitVersioning.sln which was moved out of src

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/Nerdbank.GitVersioning#912]
build.ps1 fails:

```
$ pwsh
PowerShell 7.3.3
PS C:\Projects\foreign\dotnet\Nerdbank.GitVersioning> ./build.ps1
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\Projects\foreign\dotnet\Nerdbank.GitVersioning\src\Nerdbank.GitVersioning.sln
Write-Error: Build failure
Exception: C:\Projects\foreign\dotnet\Nerdbank.GitVersioning\build.ps1:33
Line |
  33 |              throw "dotnet build failed"
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | dotnet build failed
```

It references `$PSScriptRoot\src\Nerdbank.GitVersioning.sln` here: <https://github.com/dotnet/Nerdbank.GitVersioning/blob/6bd717634efeadbae032f87c83dec93c548bcaa2/build.ps1#L18>

but `src\Nerdbank.GitVersioning.sln` was moved to `Nerdbank.GitVersioning.sln` in commit 3c38b4d178ff5ef5a6a7ace778560ec3f8b4cb43.

**Comment by AArnott** [comment]
I still have a `build.ps1` script in this repo? 🤣

Nice catch. I should probably fix that. Feel free to send a PR if you get to it first.
