### ISSUE TITLE
Nerdbank.GitVersioning used with WixToolset Bundle projects

### ISSUE THREAD

**Issue by maniglia** [dotnet/Nerdbank.GitVersioning#913]
I have the following error message when i want to use Nerdbank.GitVersioning on WixToolset Bundle (output .exe) project:
 _CodeDomProvider not available for language: wix. No version info will be embedded into assembly._

The property <NBGV_EmitThisAssemblyClass>false</NBGV_EmitThisAssemblyClass> it doesn't solve the problem.

Do you think this can be handled in [AssemblyVersionInfo.cs](https://github.com/dotnet/Nerdbank.GitVersioning/blob/6d30af47025b6af6e094e6054b67dc12a18b054f/src/Nerdbank.GitVersioning.Tasks/AssemblyVersionInfo.cs)?

**Comment by maniglia** [comment]
As a workaround using this `<GenerateAssemblyVersionInfo>false</GenerateAssemblyVersionInfo>` it's possible to use Nerdbank.GitVersioning in Wix Bundle projects.

What do you think about the following solution?

I would add the following lines in _Nerdbank.GitVersioning.targets_ files to the line: _42_
`<!-- Suppress assembly version info generation for WixToolset Bundle project. -->`
`<GenerateAssemblyVersionInfo Condition=" '$(GenerateAssemblyVersionInfo)' == '' and '$(Language)' == 'wix' and '$(TargetExt)' == '.exe' ">false</GenerateAssemblyVersionInfo>`

**Comment by AArnott** [comment]
Your workaround and proposed code change looks good to me. What if you drop the `$(TargetExt)` part of the condition though, since that seems irrelevant. Wanna send a PR?

**Comment by maniglia** [comment]
Yes, I will send a PR shortly.
