### ISSUE TITLE
'Cloud build not detected' on TeamCity 2022.10.3

### ISSUE THREAD

**Issue by GurdipS5** [dotnet/Nerdbank.GitVersioning#914]
Hi,
I am using TeamCity 2022.10.3 and get an error when running nbgv cloud:

  No cloud build detected.

I don't get any more information. I recently updated TeamCity but this was wokring before.

Any help appreciated.

**Comment by AArnott** [comment]
I don't use TeamCity, but their docs have historically been public and given instruction that we needed to build the support found in: 
https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/src/NerdBank.GitVersioning/CloudBuildServices/TeamCity.cs

If you'd care to review the TeamCity docs and update the file, I'd accept a PR.
