### ISSUE TITLE
Unable to load DLL 'git2-b7bad55' or one of its dependencies: The specified module could not be found.

### ISSUE THREAD

**Issue by GurdipS5** [dotnet/Nerdbank.GitVersioning#919]
Hi,
I am trying to run a Pulumi program (basically a dotnet core console application) on Windows Server 2022. Using NBGV 3.5.119

I set the env var NBGV_GitEngine=LibGit2 as I was getting error about a commit sha not found, now I get this;

MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:  ---> System.DllNotFoundException: Unable to load DLL 'git2-b7bad55' or one of its dependencies: The specified module could not be found. (0x8007007E) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary() in /_/LibGit2Sharp/Core/NativeMethods.cs:line 148 [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods..cctor() in /_/LibGit2Sharp/Core/NativeMethods.cs:line 54 [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    --- End of inner exception stack trace --- [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.Proxy.git_libgit2_opts_set_search_path(ConfigurationLevel level, String path) in /_/LibGit2Sharp/Core/Proxy.cs:line 3423 [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths) in /_/LibGit2Sharp/GlobalSettings.cs:line 337 [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.LibGit2.LibGit2Context.OpenGitRepo(String path, Boolean useDefaultConfigSearchPaths) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.LibGit2.LibGit2Context..ctor(String workingTreeDirectory, String dotGitPath, String committish) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner() [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]

Build FAILED.

C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:  ---> System.DllNotFoundException: Unable to load DLL 'git2-b7bad55' or one of its dependencies: The specified module could not be found. (0x8007007E) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init() [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary() in /_/LibGit2Sharp/Core/NativeMethods.cs:line 148 [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods..cctor() in /_/LibGit2Sharp/Core/NativeMethods.cs:line 54 [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    --- End of inner exception stack trace --- [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.Core.Proxy.git_libgit2_opts_set_search_path(ConfigurationLevel level, String path) in /_/LibGit2Sharp/Core/Proxy.cs:line 3423 [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths) in /_/LibGit2Sharp/GlobalSettings.cs:line 337 [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.LibGit2.LibGit2Context.OpenGitRepo(String path, Boolean useDefaultConfigSearchPaths) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.LibGit2.LibGit2Context..ctor(String workingTreeDirectory, String dotGitPath, String committish) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable) [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\Nerdbank.GitVersioning.Inner.targets(17,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner() [C:\Users\Administrator\.nuget\packages\nerdbank.gitversioning\3.5.119\build\PrivateP2PCaching.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.33

Is there a way to fix this?

**Comment by GurdipS5** [comment]
The issue I got before the env key was: https://github.com/dotnet/Nerdbank.GitVersioning/issues/595 

I can't yet fix either?

**Comment by AArnott** [comment]
I can repro this. I'll check it out.

**Comment by AArnott** [comment]
It appears this is broken for two reasons: on .NET it fails because the `lib` folder in the native binaries was changed to `runtimes`, and on .NET Framework it broke because adding the native folder to the PATH no longer works.
