### ISSUE TITLE
Set PrereleaseVersion from MSBuild

### ISSUE THREAD

**Issue by mivor** [dotnet/Nerdbank.GitVersioning#924]
I have a packaged desktop application that is shipped to end users.
The release cycle is:
- after feature developement is done we build 1.1.xx-rc.1
- this is tested internally for bugs
- if there are fixes needed we ship 1.1.zz-rc.2
- after the testing is done we ship 1.1.zz

What I would like to do is that once we have 1.1.25-rc.2, and it passed testing, to be able to build a 1.1.25 which would be the same commit, without the pre-release tag.

If I do this by modifying the version.json, I would get a new version number, which confuses the QA and the client, since they tested 1.1.25-rc.2, and now we release 1.1.26.

My idea was to be able to set the PrereleaseVersion from MSBuild, so that I can build the same commit as -rc.2 and without.
If the change is accepted by you, I can work on a PR for it.

Do you have any other recommendations on how to achieve this?

**Comment by AArnott** [comment]
It's something of the philosophy for NB.GV that a commit cannot be both stable and unstable, except for the 'non-public release branch' scenario, which doesn't fit your release branch scenario.
You presumably have a 1.1 branch where you stabilize work. The thinking here goes "ok, you've done all this testing and satisfied yourself that this is stable. Isn't it worth pushing a commit that indicates that the branch is now stable?"

If the 3rd integer version bump is getting you down though (which seems petty IMHO, but some folks are bothered by it, I get it), you can change the version.json to move the version height integer to another position. For example `1.1.0-rc.2.{height}`, and when you're stable, just push a commit that removes the entire unstable suffix and you'll get a 1.1.0(.x) build of your software.
This is what folks who care about controlling the first 3 integers of the version can do with NB.GV.

In addition, you can do _anything_ you want with msbuild by adding an msbuild target that runs after the `GetBuildVersion` target and change properties around.
