### ISSUE TITLE
3.6 Release Date?

### ISSUE THREAD

**Issue by adc-cjewett** [dotnet/Nerdbank.GitVersioning#926]
We ran into this issue recently (https://github.com/dotnet/Nerdbank.GitVersioning/pull/892) and we were curious when the 3.6 release date would be happening. We got everything wired up using the CI alpha builds from https://dev.azure.com/andrewarnott/OSS/_artifacts/feed/PublicCI but some are hesitant to use an alpha package.

**Comment by AArnott** [comment]
We can probably push out a release in the next week or so. I just want to review the active issues to see if there are any regressions or other easy-pickings to include in the release. 
If it would help, I can push another prerelease to nuget.org right away.

**Comment by adc-cjewett** [comment]
A prerelease would be good so we don't need to add the NuGet source but if a release is coming within a week or two then I don't think we're too worried about it. Thanks for such a quick response!

**Comment by AArnott** [comment]
https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.6.128
