### ISSUE TITLE
Cake.GitVersioning v3.6+ doesn't support Cake v2.x anymore

### ISSUE THREAD

**Issue by kapsiR** [dotnet/Nerdbank.GitVersioning#934]
> Could not load <...>\Addins\Cake.GitVersioning.3.6.128\lib\net6.0\Cake.GitVersioning.dll (**missing Cake.Core, Version=3.0.0.0**, Culture=neutral, PublicKeyToken=null))

Is this an intended change in `v3.6` (3.6.99-alpha+56b1dacf89)? I couldn't find anything regarding it in the release notes...

**Comment by Sam13** [comment]
Similar issue here:

```Nerdbank.GitVersioning.Inner.targets(17, 5): [MSB4062] The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task could not be loaded from the assembly C:\Users\USER\.nuget\packages\nerdbank.gitversioning\3.6.128\build\MSBuildCore/Nerdbank.GitVersioning.Tasks.dll. Could not load file or assembly 'System.Runtime.Loader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.```

Seems to work when SDK in _globals.json_ is .NET 6 or above but e.g. not with .NET Core 3.1

**Comment by kapsiR** [comment]
To clarify, for me it's more of a documentation issue rather than an issue of the addin itself.  
Pinning the version of an addin is recommended and avoids issues with updated packages in CI.

If such changes are reflected in the release notes or with a major version upgrade, this should be ok I think.

**Comment by AArnott** [comment]
Thank you for the feedback. I've updated [the release notes](https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.6.128).

I'm not a Cake user myself, so my acceptance of the Dependabot PR to upgrade the reference assembly was made somewhat ignorantly of how it would likely impact users. Would Cake v3 users be able to use NB.GV if it were compiled against Cake v2?

**Comment by kapsiR** [comment]
> Would Cake v3 users be able to use NB.GV if it were compiled against Cake v2?

Maybe I find some time tonight to check this...

**Comment by AArnott** [comment]
I'm about to release a servicing fix for 3.6 and would like to close this issue as part of that. @kapsiR how is that testing coming? Should I downgrade to referencing Cake v2 again?

**Comment by kapsiR** [comment]
Sorry for the delay, my time in the evening is very limited at the moment...

As of my tests, it seems to work with a warning (Cake v3.0.0 and Cake.GitVersioning built with Cake.Core v2.3.0):

> The assembly 'Cake.GitVersioning, Version=3.7.6.38638, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (2.3.0).
For best compatibility it should target Cake.Core version 3.0.0.
