### ISSUE TITLE
Upgrading from 3.5.119 to 3.6.132 breaks commit id for NPM

### ISSUE THREAD

**Issue by woppa684** [dotnet/Nerdbank.GitVersioning#943]
version.json
```
{
  "$schema":  "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version":  "7.1.0-next.{height}",
  "publicReleaseRefSpec":  [
    "^refs/heads/releases/v\\d+\\.\\d+$"
  ]
}
```

Output of get-version for 3.5.119
```
Version:                      7.1.0
AssemblyVersion:              7.1.0.0
AssemblyInformationalVersion: 7.1.0-next.16+38d39d2671
NuGetPackageVersion:          7.1.0-next.16.g38d39d2671
NpmPackageVersion:            7.1.0-next.16.g38d39d2671
```

Output of get-version for 3.6.132
```
Version:                      7.1.0
AssemblyVersion:              7.1.0.0
AssemblyInformationalVersion: 7.1.0-next.16+38d39d2671
NuGetPackageVersion:          7.1.0-next.16.g38d39d2671
NpmPackageVersion:            7.1.0-next.16
```

Is this related to this commit? https://github.com/dotnet/Nerdbank.GitVersioning/commit/5e1adb525ffafaa91f3ae54cc86e10efcdf710b7

So, we use this to make distinct prereleases, should we switch to using the NuGetPackageVersion instead?

**Comment by AArnott** [comment]
I was wondering myself today if perhaps I had been mistaken in the belief behind that commit that NPM doesn't support the `.commitID` syntax in the version. It sounds like you agree that was a mistake. I wonder what led me to believe it was being dropped. I'll bring it back.

**Comment by woppa684** [comment]
Thanks for the quick repsonse! As far as I now, NPM just [follows](https://docs.npmjs.com/about-semantic-versioning) the [semver spec](https://semver.org/#spec-item-9), and any dot-separated prerelease identifiers after a hyphen are ok Now we'll just wait for a release :)

**Comment by woppa684** [comment]
@AArnott Any idea when a new release will be made? We have more and more repositories that need to revert now ...
