### ISSUE TITLE
prerelease tag based on branch name

### ISSUE THREAD

**Issue by BoBiene** [dotnet/Nerdbank.GitVersioning#944]
Hi,

is it possible to add a prerelease tag automatically in ci builds based on the branch name (pattern)?
I have branch names like ``feature/xyZ`` and i would like to add in ci build the ``'xyZ'`` as prerelease tag to the version automatically.

Is this possible?

**Comment by AArnott** [comment]
It's possible if you write a custom MSBuild target that runs with `AfterTargets="GetBuildVersion"`. 
NB.GV sets a variety of msbuild properties that you can read and change to customize all you want.
That said it's against NB.GV's design to let the branch name do anything other than determine the boolean value described by `publicReleaseRefSpec`, so it will not include this feature built-in.
