### ISSUE TITLE
Switch off AssemblyVersion overwrite through global setting

### ISSUE THREAD

**Issue by Silentmopp** [dotnet/Nerdbank.GitVersioning#970]
Is there a possibility in Nerdbank to skip updating the AssemblyVersion?
The AssemblyVersion configured in csproj files and calculated through MsBuild should win.

**Reason:**
Our software contains thousands of assemblies in multiple Git repositories. We are currently transitioning from .NET Framework to .Net Core and NuGet packages. Using Nerbank for the version calculation is quite comfortable and suits most of our needs. Thumbs up!

Due to historical reasons our assemblies have different AssemblyVersions, like 1.0.0.0, 1.1.0.0, 2.0.0.0, ... which must not be touched anymore. We are working backward compatible and just replacing parts of the software with a new update. Increasing the AssemblyVersion is producing runtime errors after Update/Upgrade of our installed base.

For new projects we could pin the AssemblyVersion through version.json in root like described here
https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/versionJson.md

For our exisiting code base we would require the possibility to switch off the update of the AssemblyVersion. Creating specific version.json files, to configure the different AssemblyVersions within a Git repository, would be a huge overhead. 

Short:
Switch off AssemblyVersion update through a global setting (msbuild switch, Directory.Build.targets, Directory.Packages.props, ...)
Note: Nerdbank should still update AssemblyFileVersion and AssemblyInformationVersion

**Comment by AArnott** [comment]
I don't think you'd need to write a custom task. Just author an msbuild target that runs after GetBuildVersion and rewrites the AssemblyVersion property with its original value, which you could have backed up before. For example, consider this .targets file, which you could import via Directory.Build.targets so that all your projects get it automatically:

```xml
<PropertyGroup>
   <OriginalAssemblyVersion>$(AssemblyVersion)</OriginalAssemblyVersion>
</PropertyGroup>

<Target Name="RestoreAssemblyVersion" AfterTargets="GetBuildVersion">
   <PropertyGroup>
      <AssemblyVersion>$(OriginalAssemblyVersion)</AssemblyVersion>
   </PropertyGroup>
</Target>
```

I haven't tested this, but I think this should work, and should be easy to apply.

**Comment by Silentmopp** [comment]
> I don't think you'd need to write a custom task. Just author an msbuild target that runs after GetBuildVersion and rewrites the AssemblyVersion property with its original value, which you could have backed up before. For example, consider this .targets file, which you could import via Directory.Build.targets so that all your projects get it automatically:
> 
> ```
> <PropertyGroup>
>    <OriginalAssemblyVersion>$(AssemblyVersion)</OriginalAssemblyVersion>
> </PropertyGroup>
> 
> <Target Name="RestoreAssemblyVersion" AfterTargets="GetBuildVersion">
>    <PropertyGroup>
>       <AssemblyVersion>$(OriginalAssemblyVersion)</AssemblyVersion>
>    </PropertyGroup>
> </Target>
> ```

Tried @AArnott proposal and it works fine so far. Luckily we have cleaned up most of the AssemblyInfo.cs files and have no AssemblyVersion/AssemblyFileVersion property there anymore. In case its still there msbuild throws "error CS0579: Duplicate 'AssemblyVersion' attribute" like @KalleOlaviNiemitalo mentioned correctly.

In case of projects not having an AssemblyVersion property in the csporj the compilation failes with msbuild error "CS7034: The specified version string '' does not conform to the required format - major[.minor[.build[.revision]]]". 
-> Added a second statement to set default 1.0.0.0 in case its empty.

```
<AssemblyVersion Condition="'$(AssemblyVersion)' != ''">$(OriginalAssemblyVersion)</AssemblyVersion>
<AssemblyVersion Condition="'$(AssemblyVersion)' == ''">1.0.0.0</AssemblyVersion>
```

Not the best solution I could think off ;-) but we can control it for the whole repository this way. Thanks!

**Comment by AArnott** [comment]
Great. Rather than 1.0.0.0 as the default, you could just avoid setting it, allowing NB.GV to set it. Unless you want 1.0.0.0 to be the default.
I'm going to close the issue as addressed, since we typically don't add settings for one user when a workaround is readily available.
