### ISSUE TITLE
MyPropertySetter example should specify BeforeTargets=Build

### ISSUE THREAD

**Issue by carlin-q-scott** [dotnet/Nerdbank.GitVersioning#975]
The example for setting custom properties using Nerdbank properties doesn't work reliably because it doesn't have a BeforeTargets like this:
```xml
<Target Name="MyPropertySetter" DependsOnTargets="GetBuildVersion" BeforeTargets="Build">
```
## source:
https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/msbuild.md#custom-build-authoring

**Comment by AArnott** [comment]
The docs don't talk about when to schedule your target, as that depends on what else your target does. It only purports to describe how to reliably consume NB.GV properties. The `DependsOnTargets` attribute is sufficient for that. 
Whether you use `BeforeTargets`, `AfterTargets`, or _another_ target has `DependsOnTargets="MyPropertySetter"` depends on your situation.

**Comment by AArnott** [comment]
As it is, `BeforeTargets="Build"` would fail to run your target if someone built the `Pack` target instead of `Build` (or any number of other targets that might be called directly. So you really should think about what really consumes your properties and arrange for it to run before _that_ particular thing.

**Comment by carlin-q-scott** [comment]
@AArnott Doesn't `Build` still execute for pack unless you explicitly use --no-build?

My personal opinion is that examples should work for most people without further modification, and the current example does not. It likely doesn't work for anyone without further modification, and the documentation does not mention that. Could you add your description to the documentation so that people know to add a Before/After or Depends somewhere in order for this to work as expected?

**Comment by AArnott** [comment]
Sure. I can call that out.
