### ISSUE TITLE
versionHeightOffset doesn't work

### ISSUE THREAD

**Issue by Thiocyanite** [dotnet/Nerdbank.GitVersioning#979]
I'm trying to add nerdbank.gitversioning to existing project. 
It shows Major.Minor.Build.Commit_height
![image](https://github.com/dotnet/Nerdbank.GitVersioning/assets/39627677/1f04a165-72da-4064-9704-4388289211c8)
But in this project it requires adding offset. Unfortunately adding versionHeightOffset (no matter if it's positive or negative or zero value) zeroes the last integer
![image](https://github.com/dotnet/Nerdbank.GitVersioning/assets/39627677/ac1d6370-6e85-4d1e-85d1-8c423dcd04ee)

**Comment by AArnott** [comment]
You have to commit your change before the build picks it up. 
Please refer to https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/versionJson.md for this tip and others.
