### ISSUE TITLE
How auto increment the build number on every time the project is built?

### ISSUE THREAD

**Issue by asparatu** [dotnet/Nerdbank.GitVersioning#981]
how can you increment the build number every time the project is built? 

I am using this in asp.net core 7 WebApi in vs code. Even when a release build is done, it does not increment the build number but does append the git repo version.

version.json
```json
{
  "$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/main/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.0",
  "assemblyVersion": {
    "precision": "build"
  },
  "publicReleaseRefSpec": [
    "^refs/heads/master$",
    "^refs/heads/v\\d+(?:\\.\\d+)?$"
  ],
  "release": {
    "versionIncrement": "build"
  }
}
```

**Comment by AArnott** [comment]
Nerdbank.GitVersioning always computes a version based on git history. It increments with every git commit.
It does _not_ increment based on how many times you build a project. That would be impossible as nothing on a build machine tracks how many times a build occurred.

If you want the version to increment based on build count, you should look to your build provider for an environment variable or whatever they may offer that tracks build counts and hook that into your version.
