### ISSUE TITLE
New feature - Command "prepare-release"  with a paremeter for add a prefix to the commit's

### ISSUE THREAD

**Issue by fmacavilca** [dotnet/Nerdbank.GitVersioning#991]
**Please Describe The Problem To Be Solved:**
In our solution, for every commit generated, we have a format. In this case, we use the "JIRA" card format, for example "LM-xxx-{commit message}". So when the command "prepare-release" is executed, it generates two commits. We need to add this prefix to every commit. So we ask if we can collaborate to add this new feature, which should be an optional parameter to the command.

Actual value : "Set version to '2.1'"
Expected value: "LM-1450 - Set version '2.1'"

**Comment by AArnott** [comment]
Sure. I'll take that if you create a PR. Thanks for checking.

**Comment by AArnott** [comment]
Maybe expose the parameter not as necessarily a *prefix*, but as a format specifier. So it could be this:

```
--commit-message-pattern "LM-123-{0}"
```
in your case, but someone else could add a suffix if they wanted.

**Comment by fmacavilca** [comment]
Yes, that sounds great. I'm going to do that using a pattern. Thanks for your advice.

**Comment by fmacavilca** [comment]
Hi @AArnott  Can you give me permission to push my branch to this repo to create my pull request? Thanks

**Comment by AArnott** [comment]
Nope. The way this works is you fork my repo, push to your fork, then send me a pull request.

**Comment by fmacavilca** [comment]
I understand. Okay,  perfect. thanks
