### ISSUE TITLE
I have a problem building the solution

### ISSUE THREAD

**Issue by fmacavilca** [dotnet/Nerdbank.GitVersioning#992]
I followed the steps that were in "CONTRIBUTING.md," and I got this error. What could I be missing?
![image](https://github.com/dotnet/Nerdbank.GitVersioning/assets/30184580/02a6ad11-bbfe-48fa-8ca0-fb42c60e5873)

**Comment by AArnott** [comment]
Did you build the NPM package without first building the .sln? Building the .sln first is required. If the CONTRIB doc doesn't mention that, we should get that fixed.

**Comment by fmacavilca** [comment]
Yes, I build first the .sln before building the NPM package.  I got the same error

**Comment by AArnott** [comment]
Fixed in the v3.6 branch. The master branch will be fixed via merging forward a bit later.

**Comment by fmacavilca** [comment]
That's great. Thanks
